-- MySQL Script generated by MySQL Workbench
-- Wed May 29 11:48:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema runscape
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `runscape` ;

-- -----------------------------------------------------
-- Schema runscape
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `runscape` DEFAULT CHARACTER SET utf8 ;
USE `runscape` ;

-- -----------------------------------------------------
-- Table `runscape`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_user` (
  `id` VARCHAR(36) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `password_salt` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  `disabled` TINYINT(1) NOT NULL DEFAULT 0,
  `admin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_activityType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_activityType` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(20) NULL,
  `removed` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_country` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_place` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NULL,
  `fk_country` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_place_tbl_country1_idx` (`fk_country` ASC),
  CONSTRAINT `fk_tbl_place_tbl_country1`
    FOREIGN KEY (`fk_country`)
    REFERENCES `runscape`.`tbl_country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_activity` (
  `id` VARCHAR(36) NOT NULL,
  `fk_activityType` VARCHAR(36) NOT NULL,
  `fk_user` VARCHAR(36) NOT NULL,
  `name` VARCHAR(64) NULL,
  `start_timestamp` TIMESTAMP NULL,
  `end_timestamp` TIMESTAMP NULL,
  `gpx` VARCHAR(80) NULL,
  `total_distance_km` DECIMAL(5,3) NULL DEFAULT 0,
  `total_average_speed` DECIMAL(5,3) NULL DEFAULT 0,
  `total_positive_height_diff` DECIMAL(5,0) NULL,
  `total_negative_height_diff` DECIMAL(5,0) NULL,
  `removed` TINYINT(1) NULL DEFAULT 0,
  `fk_place` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_activity_tbl_user1_idx` (`fk_user` ASC),
  INDEX `fk_tbl_activity_tbl_actvityType1_idx` (`fk_activityType` ASC),
  INDEX `fk_tbl_activity_tbl_place1_idx` (`fk_place` ASC),
  CONSTRAINT `fk_tbl_activity_tbl_user1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `runscape`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_activity_tbl_actvityType1`
    FOREIGN KEY (`fk_activityType`)
    REFERENCES `runscape`.`tbl_activityType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_activity_tbl_place1`
    FOREIGN KEY (`fk_place`)
    REFERENCES `runscape`.`tbl_place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_position` (
  `id` VARCHAR(36) NOT NULL,
  `fk_activity` VARCHAR(36) NOT NULL,
  `latitude` DECIMAL(10,6) NULL,
  `longitude` DECIMAL(10,6) NULL,
  `timestamp` TIMESTAMP NULL,
  `altitude` SMALLINT UNSIGNED NULL,
  `removed` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_position_tbl_activity_idx` (`fk_activity` ASC),
  CONSTRAINT `fk_tbl_position_tbl_activity`
    FOREIGN KEY (`fk_activity`)
    REFERENCES `runscape`.`tbl_activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_subscription` (
  `id` VARCHAR(36) NOT NULL,
  `fk_user` VARCHAR(36) NOT NULL,
  `end_timestamp` TIMESTAMP NULL,
  `start_timestamp` TIMESTAMP NULL,
  `paused` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_subscription_tbl_user1_idx` (`fk_user` ASC),
  CONSTRAINT `fk_tbl_subscription_tbl_user1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `runscape`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_session` (
  `id` VARCHAR(36) NOT NULL,
  `value` VARCHAR(32) NULL,
  `validity_timestamp` TIMESTAMP NULL,
  `fk_user` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_session_tbl_user1_idx` (`fk_user` ASC),
  CONSTRAINT `fk_tbl_session_tbl_user1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `runscape`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
