SET @SwitzerlandId = UUID();
INSERT INTO tbl_country SET id=@SwitzerlandId, name='Suisse';

INSERT INTO tbl_place (id, name, fk_country) VALUES (UUID(), 'Aeugst am Albis', @SwitzerlandId),
(UUID(), 'Affoltern am Albis', @SwitzerlandId),
(UUID(), 'Bonstetten', @SwitzerlandId),
(UUID(), 'Hausen am Albis', @SwitzerlandId),
(UUID(), 'Hedingen', @SwitzerlandId),
(UUID(), 'Kappel am Albis', @SwitzerlandId),
(UUID(), 'Knonau', @SwitzerlandId),
(UUID(), 'Maschwanden', @SwitzerlandId),
(UUID(), 'Mettmenstetten', @SwitzerlandId),
(UUID(), 'Obfelden', @SwitzerlandId),
(UUID(), 'Ottenbach', @SwitzerlandId),
(UUID(), 'Rifferswil', @SwitzerlandId),
(UUID(), 'Stallikon', @SwitzerlandId),
(UUID(), 'Wettswil am Albis', @SwitzerlandId),
(UUID(), 'Adlikon', @SwitzerlandId),
(UUID(), 'Benken (ZH)', @SwitzerlandId),
(UUID(), 'Berg am Irchel', @SwitzerlandId),
(UUID(), 'Buch am Irchel', @SwitzerlandId),
(UUID(), 'Dachsen', @SwitzerlandId),
(UUID(), 'Dorf', @SwitzerlandId),
(UUID(), 'Feuerthalen', @SwitzerlandId),
(UUID(), 'Flaach', @SwitzerlandId),
(UUID(), 'Flurlingen', @SwitzerlandId),
(UUID(), 'Andelfingen', @SwitzerlandId),
(UUID(), 'Henggart', @SwitzerlandId),
(UUID(), 'Humlikon', @SwitzerlandId),
(UUID(), 'Kleinandelfingen', @SwitzerlandId),
(UUID(), 'Laufen-Uhwiesen', @SwitzerlandId),
(UUID(), 'Marthalen', @SwitzerlandId),
(UUID(), 'Ossingen', @SwitzerlandId),
(UUID(), 'Rheinau', @SwitzerlandId),
(UUID(), 'Thalheim an der Thur', @SwitzerlandId),
(UUID(), 'Trüllikon', @SwitzerlandId),
(UUID(), 'Truttikon', @SwitzerlandId),
(UUID(), 'Volken', @SwitzerlandId),
(UUID(), 'Bachenbülach', @SwitzerlandId),
(UUID(), 'Bassersdorf', @SwitzerlandId),
(UUID(), 'Bülach', @SwitzerlandId),
(UUID(), 'Dietlikon', @SwitzerlandId),
(UUID(), 'Eglisau', @SwitzerlandId),
(UUID(), 'Embrach', @SwitzerlandId),
(UUID(), 'Freienstein-Teufen', @SwitzerlandId),
(UUID(), 'Glattfelden', @SwitzerlandId),
(UUID(), 'Hochfelden', @SwitzerlandId),
(UUID(), 'Höri', @SwitzerlandId),
(UUID(), 'Hüntwangen', @SwitzerlandId),
(UUID(), 'Kloten', @SwitzerlandId),
(UUID(), 'Lufingen', @SwitzerlandId),
(UUID(), 'Nürensdorf', @SwitzerlandId),
(UUID(), 'Oberembrach', @SwitzerlandId),
(UUID(), 'Opfikon', @SwitzerlandId),
(UUID(), 'Rafz', @SwitzerlandId),
(UUID(), 'Rorbas', @SwitzerlandId),
(UUID(), 'Wallisellen', @SwitzerlandId),
(UUID(), 'Wasterkingen', @SwitzerlandId),
(UUID(), 'Wil (ZH)', @SwitzerlandId),
(UUID(), 'Winkel', @SwitzerlandId),
(UUID(), 'Bachs', @SwitzerlandId),
(UUID(), 'Boppelsen', @SwitzerlandId),
(UUID(), 'Buchs (ZH)', @SwitzerlandId),
(UUID(), 'Dällikon', @SwitzerlandId),
(UUID(), 'Dänikon', @SwitzerlandId),
(UUID(), 'Dielsdorf', @SwitzerlandId),
(UUID(), 'Hüttikon', @SwitzerlandId),
(UUID(), 'Neerach', @SwitzerlandId),
(UUID(), 'Niederglatt', @SwitzerlandId),
(UUID(), 'Niederhasli', @SwitzerlandId),
(UUID(), 'Niederweningen', @SwitzerlandId),
(UUID(), 'Oberglatt', @SwitzerlandId),
(UUID(), 'Oberweningen', @SwitzerlandId),
(UUID(), 'Otelfingen', @SwitzerlandId),
(UUID(), 'Regensberg', @SwitzerlandId),
(UUID(), 'Regensdorf', @SwitzerlandId),
(UUID(), 'Rümlang', @SwitzerlandId),
(UUID(), 'Schleinikon', @SwitzerlandId),
(UUID(), 'Schöfflisdorf', @SwitzerlandId),
(UUID(), 'Stadel', @SwitzerlandId),
(UUID(), 'Steinmaur', @SwitzerlandId),
(UUID(), 'Weiach', @SwitzerlandId),
(UUID(), 'Bäretswil', @SwitzerlandId),
(UUID(), 'Bubikon', @SwitzerlandId),
(UUID(), 'Dürnten', @SwitzerlandId),
(UUID(), 'Fischenthal', @SwitzerlandId),
(UUID(), 'Gossau (ZH)', @SwitzerlandId),
(UUID(), 'Grüningen', @SwitzerlandId),
(UUID(), 'Hinwil', @SwitzerlandId),
(UUID(), 'Rüti (ZH)', @SwitzerlandId),
(UUID(), 'Seegräben', @SwitzerlandId),
(UUID(), 'Wald (ZH)', @SwitzerlandId),
(UUID(), 'Wetzikon (ZH)', @SwitzerlandId),
(UUID(), 'Adliswil', @SwitzerlandId),
(UUID(), 'Kilchberg (ZH)', @SwitzerlandId),
(UUID(), 'Langnau am Albis', @SwitzerlandId),
(UUID(), 'Oberrieden', @SwitzerlandId),
(UUID(), 'Richterswil', @SwitzerlandId),
(UUID(), 'Rüschlikon', @SwitzerlandId),
(UUID(), 'Thalwil', @SwitzerlandId),
(UUID(), 'Erlenbach (ZH)', @SwitzerlandId),
(UUID(), 'Herrliberg', @SwitzerlandId),
(UUID(), 'Hombrechtikon', @SwitzerlandId),
(UUID(), 'Küsnacht (ZH)', @SwitzerlandId),
(UUID(), 'Männedorf', @SwitzerlandId),
(UUID(), 'Meilen', @SwitzerlandId),
(UUID(), 'Oetwil am See', @SwitzerlandId),
(UUID(), 'Stäfa', @SwitzerlandId),
(UUID(), 'Uetikon am See', @SwitzerlandId),
(UUID(), 'Zumikon', @SwitzerlandId),
(UUID(), 'Zollikon', @SwitzerlandId),
(UUID(), 'Fehraltorf', @SwitzerlandId),
(UUID(), 'Hittnau', @SwitzerlandId),
(UUID(), 'Lindau', @SwitzerlandId),
(UUID(), 'Pfäffikon', @SwitzerlandId),
(UUID(), 'Russikon', @SwitzerlandId),
(UUID(), 'Weisslingen', @SwitzerlandId),
(UUID(), 'Wila', @SwitzerlandId),
(UUID(), 'Wildberg', @SwitzerlandId),
(UUID(), 'Dübendorf', @SwitzerlandId),
(UUID(), 'Egg', @SwitzerlandId),
(UUID(), 'Fällanden', @SwitzerlandId),
(UUID(), 'Greifensee', @SwitzerlandId),
(UUID(), 'Maur', @SwitzerlandId),
(UUID(), 'Mönchaltorf', @SwitzerlandId),
(UUID(), 'Schwerzenbach', @SwitzerlandId),
(UUID(), 'Uster', @SwitzerlandId),
(UUID(), 'Volketswil', @SwitzerlandId),
(UUID(), 'Wangen-Brüttisellen', @SwitzerlandId),
(UUID(), 'Altikon', @SwitzerlandId),
(UUID(), 'Brütten', @SwitzerlandId),
(UUID(), 'Dägerlen', @SwitzerlandId),
(UUID(), 'Dättlikon', @SwitzerlandId),
(UUID(), 'Dinhard', @SwitzerlandId),
(UUID(), 'Ellikon an der Thur', @SwitzerlandId),
(UUID(), 'Elsau', @SwitzerlandId),
(UUID(), 'Hagenbuch', @SwitzerlandId),
(UUID(), 'Hettlingen', @SwitzerlandId),
(UUID(), 'Neftenbach', @SwitzerlandId),
(UUID(), 'Pfungen', @SwitzerlandId),
(UUID(), 'Rickenbach (ZH)', @SwitzerlandId),
(UUID(), 'Schlatt (ZH)', @SwitzerlandId),
(UUID(), 'Seuzach', @SwitzerlandId),
(UUID(), 'Turbenthal', @SwitzerlandId),
(UUID(), 'Winterthur', @SwitzerlandId),
(UUID(), 'Zell (ZH)', @SwitzerlandId),
(UUID(), 'Aesch (ZH)', @SwitzerlandId),
(UUID(), 'Birmensdorf (ZH)', @SwitzerlandId),
(UUID(), 'Dietikon', @SwitzerlandId),
(UUID(), 'Geroldswil', @SwitzerlandId),
(UUID(), 'Oberengstringen', @SwitzerlandId),
(UUID(), 'Oetwil an der Limmat', @SwitzerlandId),
(UUID(), 'Schlieren', @SwitzerlandId),
(UUID(), 'Uitikon', @SwitzerlandId),
(UUID(), 'Unterengstringen', @SwitzerlandId),
(UUID(), 'Urdorf', @SwitzerlandId),
(UUID(), 'Weiningen (ZH)', @SwitzerlandId),
(UUID(), 'Zürich', @SwitzerlandId),
(UUID(), 'Stammheim', @SwitzerlandId),
(UUID(), 'Wädenswil', @SwitzerlandId),
(UUID(), 'Elgg', @SwitzerlandId),
(UUID(), 'Horgen', @SwitzerlandId),
(UUID(), 'Illnau-Effretikon', @SwitzerlandId),
(UUID(), 'Bauma', @SwitzerlandId),
(UUID(), 'Wiesendangen', @SwitzerlandId),
(UUID(), 'Aarberg', @SwitzerlandId),
(UUID(), 'Bargen (BE)', @SwitzerlandId),
(UUID(), 'Grossaffoltern', @SwitzerlandId),
(UUID(), 'Kallnach', @SwitzerlandId),
(UUID(), 'Kappelen', @SwitzerlandId),
(UUID(), 'Lyss', @SwitzerlandId),
(UUID(), 'Meikirch', @SwitzerlandId),
(UUID(), 'Radelfingen', @SwitzerlandId),
(UUID(), 'Rapperswil (BE)', @SwitzerlandId),
(UUID(), 'Schüpfen', @SwitzerlandId),
(UUID(), 'Seedorf (BE)', @SwitzerlandId),
(UUID(), 'Aarwangen', @SwitzerlandId),
(UUID(), 'Auswil', @SwitzerlandId),
(UUID(), 'Bannwil', @SwitzerlandId),
(UUID(), 'Bleienbach', @SwitzerlandId),
(UUID(), 'Busswil bei Melchnau', @SwitzerlandId),
(UUID(), 'Gondiswil', @SwitzerlandId),
(UUID(), 'Langenthal', @SwitzerlandId),
(UUID(), 'Lotzwil', @SwitzerlandId),
(UUID(), 'Madiswil', @SwitzerlandId),
(UUID(), 'Melchnau', @SwitzerlandId),
(UUID(), 'Obersteckholz', @SwitzerlandId),
(UUID(), 'Oeschenbach', @SwitzerlandId),
(UUID(), 'Reisiswil', @SwitzerlandId),
(UUID(), 'Roggwil (BE)', @SwitzerlandId),
(UUID(), 'Rohrbach', @SwitzerlandId),
(UUID(), 'Rohrbachgraben', @SwitzerlandId),
(UUID(), 'Rütschelen', @SwitzerlandId),
(UUID(), 'Schwarzhäusern', @SwitzerlandId),
(UUID(), 'Thunstetten', @SwitzerlandId),
(UUID(), 'Ursenbach', @SwitzerlandId),
(UUID(), 'Wynau', @SwitzerlandId),
(UUID(), 'Bern', @SwitzerlandId),
(UUID(), 'Bolligen', @SwitzerlandId),
(UUID(), 'Bremgarten bei Bern', @SwitzerlandId),
(UUID(), 'Kirchlindach', @SwitzerlandId),
(UUID(), 'Köniz', @SwitzerlandId),
(UUID(), 'Muri bei Bern', @SwitzerlandId),
(UUID(), 'Oberbalm', @SwitzerlandId),
(UUID(), 'Stettlen', @SwitzerlandId),
(UUID(), 'Vechigen', @SwitzerlandId),
(UUID(), 'Wohlen bei Bern', @SwitzerlandId),
(UUID(), 'Zollikofen', @SwitzerlandId),
(UUID(), 'Ittigen', @SwitzerlandId),
(UUID(), 'Ostermundigen', @SwitzerlandId),
(UUID(), 'Biel/Bienne', @SwitzerlandId),
(UUID(), 'Evilard', @SwitzerlandId),
(UUID(), 'Arch', @SwitzerlandId),
(UUID(), 'Büetigen', @SwitzerlandId),
(UUID(), 'Büren an der Aare', @SwitzerlandId),
(UUID(), 'Diessbach bei Büren', @SwitzerlandId),
(UUID(), 'Dotzigen', @SwitzerlandId),
(UUID(), 'Lengnau (BE)', @SwitzerlandId),
(UUID(), 'Leuzigen', @SwitzerlandId),
(UUID(), 'Meienried', @SwitzerlandId),
(UUID(), 'Meinisberg', @SwitzerlandId),
(UUID(), 'Oberwil bei Büren', @SwitzerlandId),
(UUID(), 'Pieterlen', @SwitzerlandId),
(UUID(), 'Rüti bei Büren', @SwitzerlandId),
(UUID(), 'Wengi', @SwitzerlandId),
(UUID(), 'Aefligen', @SwitzerlandId),
(UUID(), 'Alchenstorf', @SwitzerlandId),
(UUID(), 'Bäriswil', @SwitzerlandId),
(UUID(), 'Burgdorf', @SwitzerlandId),
(UUID(), 'Ersigen', @SwitzerlandId),
(UUID(), 'Hasle bei Burgdorf', @SwitzerlandId),
(UUID(), 'Heimiswil', @SwitzerlandId),
(UUID(), 'Hellsau', @SwitzerlandId),
(UUID(), 'Hindelbank', @SwitzerlandId),
(UUID(), 'Höchstetten', @SwitzerlandId),
(UUID(), 'Kernenried', @SwitzerlandId),
(UUID(), 'Kirchberg (BE)', @SwitzerlandId),
(UUID(), 'Koppigen', @SwitzerlandId),
(UUID(), 'Krauchthal', @SwitzerlandId),
(UUID(), 'Lyssach', @SwitzerlandId),
(UUID(), 'Mötschwil', @SwitzerlandId),
(UUID(), 'Oberburg', @SwitzerlandId),
(UUID(), 'Rüdtligen-Alchenflüh', @SwitzerlandId),
(UUID(), 'Rumendingen', @SwitzerlandId),
(UUID(), 'Rüti bei Lyssach', @SwitzerlandId),
(UUID(), 'Willadingen', @SwitzerlandId),
(UUID(), 'Wynigen', @SwitzerlandId),
(UUID(), 'Corgémont', @SwitzerlandId),
(UUID(), 'Cormoret', @SwitzerlandId),
(UUID(), 'Cortébert', @SwitzerlandId),
(UUID(), 'Courtelary', @SwitzerlandId),
(UUID(), 'La Ferrière', @SwitzerlandId),
(UUID(), 'Mont-Tramelan', @SwitzerlandId),
(UUID(), 'Orvin', @SwitzerlandId),
(UUID(), 'Renan (BE)', @SwitzerlandId),
(UUID(), 'Romont (BE)', @SwitzerlandId),
(UUID(), 'Saint-Imier', @SwitzerlandId),
(UUID(), 'Sonceboz-Sombeval', @SwitzerlandId),
(UUID(), 'Sonvilier', @SwitzerlandId),
(UUID(), 'Tramelan', @SwitzerlandId),
(UUID(), 'Villeret', @SwitzerlandId),
(UUID(), 'Sauge', @SwitzerlandId),
(UUID(), 'Péry-La Heutte', @SwitzerlandId),
(UUID(), 'Brüttelen', @SwitzerlandId),
(UUID(), 'Erlach', @SwitzerlandId),
(UUID(), 'Finsterhennen', @SwitzerlandId),
(UUID(), 'Gals', @SwitzerlandId),
(UUID(), 'Gampelen', @SwitzerlandId),
(UUID(), 'Ins', @SwitzerlandId),
(UUID(), 'Lüscherz', @SwitzerlandId),
(UUID(), 'Müntschemier', @SwitzerlandId),
(UUID(), 'Siselen', @SwitzerlandId),
(UUID(), 'Treiten', @SwitzerlandId),
(UUID(), 'Tschugg', @SwitzerlandId),
(UUID(), 'Vinelz', @SwitzerlandId),
(UUID(), 'Bätterkinden', @SwitzerlandId),
(UUID(), 'Deisswil bei Münchenbuchsee', @SwitzerlandId),
(UUID(), 'Diemerswil', @SwitzerlandId),
(UUID(), 'Fraubrunnen', @SwitzerlandId),
(UUID(), 'Jegenstorf', @SwitzerlandId),
(UUID(), 'Iffwil', @SwitzerlandId),
(UUID(), 'Mattstetten', @SwitzerlandId),
(UUID(), 'Moosseedorf', @SwitzerlandId),
(UUID(), 'Münchenbuchsee', @SwitzerlandId),
(UUID(), 'Urtenen-Schönbühl', @SwitzerlandId),
(UUID(), 'Utzenstorf', @SwitzerlandId),
(UUID(), 'Wiggiswil', @SwitzerlandId),
(UUID(), 'Wiler bei Utzenstorf', @SwitzerlandId),
(UUID(), 'Zielebach', @SwitzerlandId),
(UUID(), 'Zuzwil (BE)', @SwitzerlandId),
(UUID(), 'Adelboden', @SwitzerlandId),
(UUID(), 'Aeschi bei Spiez', @SwitzerlandId),
(UUID(), 'Frutigen', @SwitzerlandId),
(UUID(), 'Kandergrund', @SwitzerlandId),
(UUID(), 'Kandersteg', @SwitzerlandId),
(UUID(), 'Krattigen', @SwitzerlandId),
(UUID(), 'Reichenbach im Kandertal', @SwitzerlandId),
(UUID(), 'Beatenberg', @SwitzerlandId),
(UUID(), 'Bönigen', @SwitzerlandId),
(UUID(), 'Brienz (BE)', @SwitzerlandId),
(UUID(), 'Brienzwiler', @SwitzerlandId),
(UUID(), 'Därligen', @SwitzerlandId),
(UUID(), 'Grindelwald', @SwitzerlandId),
(UUID(), 'Gsteigwiler', @SwitzerlandId),
(UUID(), 'Gündlischwand', @SwitzerlandId),
(UUID(), 'Habkern', @SwitzerlandId),
(UUID(), 'Hofstetten bei Brienz', @SwitzerlandId),
(UUID(), 'Interlaken', @SwitzerlandId),
(UUID(), 'Iseltwald', @SwitzerlandId),
(UUID(), 'Lauterbrunnen', @SwitzerlandId),
(UUID(), 'Leissigen', @SwitzerlandId),
(UUID(), 'Lütschental', @SwitzerlandId),
(UUID(), 'Matten bei Interlaken', @SwitzerlandId),
(UUID(), 'Niederried bei Interlaken', @SwitzerlandId),
(UUID(), 'Oberried am Brienzersee', @SwitzerlandId),
(UUID(), 'Ringgenberg (BE)', @SwitzerlandId),
(UUID(), 'Saxeten', @SwitzerlandId),
(UUID(), 'Schwanden bei Brienz', @SwitzerlandId),
(UUID(), 'Unterseen', @SwitzerlandId),
(UUID(), 'Wilderswil', @SwitzerlandId),
(UUID(), 'Arni (BE)', @SwitzerlandId),
(UUID(), 'Biglen', @SwitzerlandId),
(UUID(), 'Bowil', @SwitzerlandId),
(UUID(), 'Brenzikofen', @SwitzerlandId),
(UUID(), 'Freimettigen', @SwitzerlandId),
(UUID(), 'Grosshöchstetten', @SwitzerlandId),
(UUID(), 'Häutligen', @SwitzerlandId),
(UUID(), 'Herbligen', @SwitzerlandId),
(UUID(), 'Kiesen', @SwitzerlandId),
(UUID(), 'Konolfingen', @SwitzerlandId),
(UUID(), 'Landiswil', @SwitzerlandId),
(UUID(), 'Linden', @SwitzerlandId),
(UUID(), 'Mirchel', @SwitzerlandId),
(UUID(), 'Münsingen', @SwitzerlandId),
(UUID(), 'Niederhünigen', @SwitzerlandId),
(UUID(), 'Oberdiessbach', @SwitzerlandId),
(UUID(), 'Oberthal', @SwitzerlandId),
(UUID(), 'Oppligen', @SwitzerlandId),
(UUID(), 'Rubigen', @SwitzerlandId),
(UUID(), 'Walkringen', @SwitzerlandId),
(UUID(), 'Worb', @SwitzerlandId),
(UUID(), 'Zäziwil', @SwitzerlandId),
(UUID(), 'Oberhünigen', @SwitzerlandId),
(UUID(), 'Allmendingen', @SwitzerlandId),
(UUID(), 'Wichtrach', @SwitzerlandId),
(UUID(), 'Clavaleyres', @SwitzerlandId),
(UUID(), 'Ferenbalm', @SwitzerlandId),
(UUID(), 'Frauenkappelen', @SwitzerlandId),
(UUID(), 'Gurbrü', @SwitzerlandId),
(UUID(), 'Kriechenwil', @SwitzerlandId),
(UUID(), 'Laupen', @SwitzerlandId),
(UUID(), 'Mühleberg', @SwitzerlandId),
(UUID(), 'Münchenwiler', @SwitzerlandId),
(UUID(), 'Neuenegg', @SwitzerlandId),
(UUID(), 'Wileroltigen', @SwitzerlandId),
(UUID(), 'Belprahon', @SwitzerlandId),
(UUID(), 'Champoz', @SwitzerlandId),
(UUID(), 'Corcelles (BE)', @SwitzerlandId),
(UUID(), 'Court', @SwitzerlandId),
(UUID(), 'Crémines', @SwitzerlandId),
(UUID(), 'Eschert', @SwitzerlandId),
(UUID(), 'Grandval', @SwitzerlandId),
(UUID(), 'Loveresse', @SwitzerlandId),
(UUID(), 'Moutier', @SwitzerlandId),
(UUID(), 'Perrefitte', @SwitzerlandId),
(UUID(), 'Reconvilier', @SwitzerlandId),
(UUID(), 'Roches (BE)', @SwitzerlandId),
(UUID(), 'Saicourt', @SwitzerlandId),
(UUID(), 'Saules (BE)', @SwitzerlandId),
(UUID(), 'Schelten', @SwitzerlandId),
(UUID(), 'Seehof', @SwitzerlandId),
(UUID(), 'Sorvilier', @SwitzerlandId),
(UUID(), 'Tavannes', @SwitzerlandId),
(UUID(), 'Rebévelier', @SwitzerlandId),
(UUID(), 'Petit-Val', @SwitzerlandId),
(UUID(), 'Valbirse', @SwitzerlandId),
(UUID(), 'La Neuveville', @SwitzerlandId),
(UUID(), 'Nods', @SwitzerlandId),
(UUID(), 'Plateau de Diesse', @SwitzerlandId),
(UUID(), 'Aegerten', @SwitzerlandId),
(UUID(), 'Bellmund', @SwitzerlandId),
(UUID(), 'Brügg', @SwitzerlandId),
(UUID(), 'Bühl', @SwitzerlandId),
(UUID(), 'Epsach', @SwitzerlandId),
(UUID(), 'Hagneck', @SwitzerlandId),
(UUID(), 'Hermrigen', @SwitzerlandId),
(UUID(), 'Jens', @SwitzerlandId),
(UUID(), 'Ipsach', @SwitzerlandId),
(UUID(), 'Ligerz', @SwitzerlandId),
(UUID(), 'Merzligen', @SwitzerlandId),
(UUID(), 'Mörigen', @SwitzerlandId),
(UUID(), 'Nidau', @SwitzerlandId),
(UUID(), 'Orpund', @SwitzerlandId),
(UUID(), 'Port', @SwitzerlandId),
(UUID(), 'Safnern', @SwitzerlandId),
(UUID(), 'Scheuren', @SwitzerlandId),
(UUID(), 'Schwadernau', @SwitzerlandId),
(UUID(), 'Studen (BE)', @SwitzerlandId),
(UUID(), 'Sutz-Lattrigen', @SwitzerlandId),
(UUID(), 'Täuffelen', @SwitzerlandId),
(UUID(), 'Walperswil', @SwitzerlandId),
(UUID(), 'Worben', @SwitzerlandId),
(UUID(), 'Twann-Tüscherz', @SwitzerlandId),
(UUID(), 'Därstetten', @SwitzerlandId),
(UUID(), 'Diemtigen', @SwitzerlandId),
(UUID(), 'Erlenbach im Simmental', @SwitzerlandId),
(UUID(), 'Oberwil im Simmental', @SwitzerlandId),
(UUID(), 'Reutigen', @SwitzerlandId),
(UUID(), 'Spiez', @SwitzerlandId),
(UUID(), 'Wimmis', @SwitzerlandId),
(UUID(), 'Stocken-Höfen', @SwitzerlandId),
(UUID(), 'Guttannen', @SwitzerlandId),
(UUID(), 'Hasliberg', @SwitzerlandId),
(UUID(), 'Innertkirchen', @SwitzerlandId),
(UUID(), 'Meiringen', @SwitzerlandId),
(UUID(), 'Schattenhalb', @SwitzerlandId),
(UUID(), 'Boltigen', @SwitzerlandId),
(UUID(), 'Lenk', @SwitzerlandId),
(UUID(), 'St. Stephan', @SwitzerlandId),
(UUID(), 'Zweisimmen', @SwitzerlandId),
(UUID(), 'Gsteig', @SwitzerlandId),
(UUID(), 'Lauenen', @SwitzerlandId),
(UUID(), 'Saanen', @SwitzerlandId),
(UUID(), 'Guggisberg', @SwitzerlandId),
(UUID(), 'Rüschegg', @SwitzerlandId),
(UUID(), 'Schwarzenburg', @SwitzerlandId),
(UUID(), 'Belp', @SwitzerlandId),
(UUID(), 'Burgistein', @SwitzerlandId),
(UUID(), 'Gerzensee', @SwitzerlandId),
(UUID(), 'Gurzelen', @SwitzerlandId),
(UUID(), 'Jaberg', @SwitzerlandId),
(UUID(), 'Kaufdorf', @SwitzerlandId),
(UUID(), 'Kehrsatz', @SwitzerlandId),
(UUID(), 'Kirchdorf (BE)', @SwitzerlandId),
(UUID(), 'Kirchenthurnen', @SwitzerlandId),
(UUID(), 'Lohnstorf', @SwitzerlandId),
(UUID(), 'Mühlethurnen', @SwitzerlandId),
(UUID(), 'Niedermuhlern', @SwitzerlandId),
(UUID(), 'Riggisberg', @SwitzerlandId),
(UUID(), 'Rüeggisberg', @SwitzerlandId),
(UUID(), 'Rümligen', @SwitzerlandId),
(UUID(), 'Seftigen', @SwitzerlandId),
(UUID(), 'Toffen', @SwitzerlandId),
(UUID(), 'Uttigen', @SwitzerlandId),
(UUID(), 'Wattenwil', @SwitzerlandId),
(UUID(), 'Wald (BE)', @SwitzerlandId),
(UUID(), 'Eggiwil', @SwitzerlandId),
(UUID(), 'Langnau im Emmental', @SwitzerlandId),
(UUID(), 'Lauperswil', @SwitzerlandId),
(UUID(), 'Röthenbach im Emmental', @SwitzerlandId),
(UUID(), 'Rüderswil', @SwitzerlandId),
(UUID(), 'Schangnau', @SwitzerlandId),
(UUID(), 'Signau', @SwitzerlandId),
(UUID(), 'Trub', @SwitzerlandId),
(UUID(), 'Trubschachen', @SwitzerlandId),
(UUID(), 'Amsoldingen', @SwitzerlandId),
(UUID(), 'Blumenstein', @SwitzerlandId),
(UUID(), 'Buchholterberg', @SwitzerlandId),
(UUID(), 'Eriz', @SwitzerlandId),
(UUID(), 'Fahrni', @SwitzerlandId),
(UUID(), 'Heiligenschwendi', @SwitzerlandId),
(UUID(), 'Heimberg', @SwitzerlandId),
(UUID(), 'Hilterfingen', @SwitzerlandId),
(UUID(), 'Homberg', @SwitzerlandId),
(UUID(), 'Horrenbach-Buchen', @SwitzerlandId),
(UUID(), 'Oberhofen am Thunersee', @SwitzerlandId),
(UUID(), 'Oberlangenegg', @SwitzerlandId),
(UUID(), 'Pohlern', @SwitzerlandId),
(UUID(), 'Schwendibach', @SwitzerlandId),
(UUID(), 'Sigriswil', @SwitzerlandId),
(UUID(), 'Steffisburg', @SwitzerlandId),
(UUID(), 'Teuffenthal (BE)', @SwitzerlandId),
(UUID(), 'Thierachern', @SwitzerlandId),
(UUID(), 'Thun', @SwitzerlandId),
(UUID(), 'Uebeschi', @SwitzerlandId),
(UUID(), 'Uetendorf', @SwitzerlandId),
(UUID(), 'Unterlangenegg', @SwitzerlandId),
(UUID(), 'Wachseldorn', @SwitzerlandId),
(UUID(), 'Zwieselberg', @SwitzerlandId),
(UUID(), 'Forst-Längenbühl', @SwitzerlandId),
(UUID(), 'Affoltern im Emmental', @SwitzerlandId),
(UUID(), 'Dürrenroth', @SwitzerlandId),
(UUID(), 'Eriswil', @SwitzerlandId),
(UUID(), 'Huttwil', @SwitzerlandId),
(UUID(), 'Lützelflüh', @SwitzerlandId),
(UUID(), 'Rüegsau', @SwitzerlandId),
(UUID(), 'Sumiswald', @SwitzerlandId),
(UUID(), 'Trachselwald', @SwitzerlandId),
(UUID(), 'Walterswil (BE)', @SwitzerlandId),
(UUID(), 'Wyssachen', @SwitzerlandId),
(UUID(), 'Attiswil', @SwitzerlandId),
(UUID(), 'Berken', @SwitzerlandId),
(UUID(), 'Bettenhausen', @SwitzerlandId),
(UUID(), 'Farnern', @SwitzerlandId),
(UUID(), 'Graben', @SwitzerlandId),
(UUID(), 'Heimenhausen', @SwitzerlandId),
(UUID(), 'Herzogenbuchsee', @SwitzerlandId),
(UUID(), 'Inkwil', @SwitzerlandId),
(UUID(), 'Niederbipp', @SwitzerlandId),
(UUID(), 'Niederönz', @SwitzerlandId),
(UUID(), 'Oberbipp', @SwitzerlandId),
(UUID(), 'Ochlenberg', @SwitzerlandId),
(UUID(), 'Rumisberg', @SwitzerlandId),
(UUID(), 'Seeberg', @SwitzerlandId),
(UUID(), 'Thörigen', @SwitzerlandId),
(UUID(), 'Walliswil bei Niederbipp', @SwitzerlandId),
(UUID(), 'Walliswil bei Wangen', @SwitzerlandId),
(UUID(), 'Wangen an der Aare', @SwitzerlandId),
(UUID(), 'Wangenried', @SwitzerlandId),
(UUID(), 'Wiedlisbach', @SwitzerlandId),
(UUID(), 'Wolfisberg', @SwitzerlandId),
(UUID(), 'Doppleschwand', @SwitzerlandId),
(UUID(), 'Entlebuch', @SwitzerlandId),
(UUID(), 'Flühli', @SwitzerlandId),
(UUID(), 'Hasle (LU)', @SwitzerlandId),
(UUID(), 'Romoos', @SwitzerlandId),
(UUID(), 'Schüpfheim', @SwitzerlandId),
(UUID(), 'Werthenstein', @SwitzerlandId),
(UUID(), 'Escholzmatt-Marbach', @SwitzerlandId),
(UUID(), 'Aesch (LU)', @SwitzerlandId),
(UUID(), 'Altwis', @SwitzerlandId),
(UUID(), 'Ballwil', @SwitzerlandId),
(UUID(), 'Emmen', @SwitzerlandId),
(UUID(), 'Ermensee', @SwitzerlandId),
(UUID(), 'Eschenbach (LU)', @SwitzerlandId),
(UUID(), 'Hitzkirch', @SwitzerlandId),
(UUID(), 'Hochdorf', @SwitzerlandId),
(UUID(), 'Hohenrain', @SwitzerlandId),
(UUID(), 'Inwil', @SwitzerlandId),
(UUID(), 'Rain', @SwitzerlandId),
(UUID(), 'Römerswil', @SwitzerlandId),
(UUID(), 'Rothenburg', @SwitzerlandId),
(UUID(), 'Schongau', @SwitzerlandId),
(UUID(), 'Adligenswil', @SwitzerlandId),
(UUID(), 'Buchrain', @SwitzerlandId),
(UUID(), 'Dierikon', @SwitzerlandId),
(UUID(), 'Ebikon', @SwitzerlandId),
(UUID(), 'Gisikon', @SwitzerlandId),
(UUID(), 'Greppen', @SwitzerlandId),
(UUID(), 'Honau', @SwitzerlandId),
(UUID(), 'Horw', @SwitzerlandId),
(UUID(), 'Kriens', @SwitzerlandId),
(UUID(), 'Luzern', @SwitzerlandId),
(UUID(), 'Malters', @SwitzerlandId),
(UUID(), 'Meggen', @SwitzerlandId),
(UUID(), 'Meierskappel', @SwitzerlandId),
(UUID(), 'Root', @SwitzerlandId),
(UUID(), 'Schwarzenberg', @SwitzerlandId),
(UUID(), 'Udligenswil', @SwitzerlandId),
(UUID(), 'Vitznau', @SwitzerlandId),
(UUID(), 'Weggis', @SwitzerlandId),
(UUID(), 'Beromünster', @SwitzerlandId),
(UUID(), 'Büron', @SwitzerlandId),
(UUID(), 'Buttisholz', @SwitzerlandId),
(UUID(), 'Eich', @SwitzerlandId),
(UUID(), 'Geuensee', @SwitzerlandId),
(UUID(), 'Grosswangen', @SwitzerlandId),
(UUID(), 'Hildisrieden', @SwitzerlandId),
(UUID(), 'Knutwil', @SwitzerlandId),
(UUID(), 'Mauensee', @SwitzerlandId),
(UUID(), 'Neuenkirch', @SwitzerlandId),
(UUID(), 'Nottwil', @SwitzerlandId),
(UUID(), 'Oberkirch', @SwitzerlandId),
(UUID(), 'Rickenbach (LU)', @SwitzerlandId),
(UUID(), 'Ruswil', @SwitzerlandId),
(UUID(), 'Schenkon', @SwitzerlandId),
(UUID(), 'Schlierbach', @SwitzerlandId),
(UUID(), 'Sempach', @SwitzerlandId),
(UUID(), 'Sursee', @SwitzerlandId),
(UUID(), 'Triengen', @SwitzerlandId),
(UUID(), 'Wolhusen', @SwitzerlandId),
(UUID(), 'Alberswil', @SwitzerlandId),
(UUID(), 'Altbüron', @SwitzerlandId),
(UUID(), 'Altishofen', @SwitzerlandId),
(UUID(), 'Dagmersellen', @SwitzerlandId),
(UUID(), 'Ebersecken', @SwitzerlandId),
(UUID(), 'Egolzwil', @SwitzerlandId),
(UUID(), 'Ettiswil', @SwitzerlandId),
(UUID(), 'Fischbach', @SwitzerlandId),
(UUID(), 'Gettnau', @SwitzerlandId),
(UUID(), 'Grossdietwil', @SwitzerlandId),
(UUID(), 'Hergiswil bei Willisau', @SwitzerlandId),
(UUID(), 'Luthern', @SwitzerlandId),
(UUID(), 'Menznau', @SwitzerlandId),
(UUID(), 'Nebikon', @SwitzerlandId),
(UUID(), 'Pfaffnau', @SwitzerlandId),
(UUID(), 'Reiden', @SwitzerlandId),
(UUID(), 'Roggliswil', @SwitzerlandId),
(UUID(), 'Schötz', @SwitzerlandId),
(UUID(), 'Ufhusen', @SwitzerlandId),
(UUID(), 'Wauwil', @SwitzerlandId),
(UUID(), 'Wikon', @SwitzerlandId),
(UUID(), 'Zell (LU)', @SwitzerlandId),
(UUID(), 'Willisau', @SwitzerlandId),
(UUID(), 'Altdorf (UR)', @SwitzerlandId),
(UUID(), 'Andermatt', @SwitzerlandId),
(UUID(), 'Attinghausen', @SwitzerlandId),
(UUID(), 'Bauen', @SwitzerlandId),
(UUID(), 'Bürglen (UR)', @SwitzerlandId),
(UUID(), 'Erstfeld', @SwitzerlandId),
(UUID(), 'Flüelen', @SwitzerlandId),
(UUID(), 'Göschenen', @SwitzerlandId),
(UUID(), 'Gurtnellen', @SwitzerlandId),
(UUID(), 'Hospental', @SwitzerlandId),
(UUID(), 'Isenthal', @SwitzerlandId),
(UUID(), 'Realp', @SwitzerlandId),
(UUID(), 'Schattdorf', @SwitzerlandId),
(UUID(), 'Seedorf (UR)', @SwitzerlandId),
(UUID(), 'Seelisberg', @SwitzerlandId),
(UUID(), 'Silenen', @SwitzerlandId),
(UUID(), 'Sisikon', @SwitzerlandId),
(UUID(), 'Spiringen', @SwitzerlandId),
(UUID(), 'Unterschächen', @SwitzerlandId),
(UUID(), 'Wassen', @SwitzerlandId),
(UUID(), 'Einsiedeln', @SwitzerlandId),
(UUID(), 'Gersau', @SwitzerlandId),
(UUID(), 'Feusisberg', @SwitzerlandId),
(UUID(), 'Freienbach', @SwitzerlandId),
(UUID(), 'Wollerau', @SwitzerlandId),
(UUID(), 'Küssnacht (SZ)', @SwitzerlandId),
(UUID(), 'Altendorf', @SwitzerlandId),
(UUID(), 'Galgenen', @SwitzerlandId),
(UUID(), 'Innerthal', @SwitzerlandId),
(UUID(), 'Lachen', @SwitzerlandId),
(UUID(), 'Reichenburg', @SwitzerlandId),
(UUID(), 'Schübelbach', @SwitzerlandId),
(UUID(), 'Tuggen', @SwitzerlandId),
(UUID(), 'Vorderthal', @SwitzerlandId),
(UUID(), 'Wangen (SZ)', @SwitzerlandId),
(UUID(), 'Alpthal', @SwitzerlandId),
(UUID(), 'Arth', @SwitzerlandId),
(UUID(), 'Illgau', @SwitzerlandId),
(UUID(), 'Ingenbohl', @SwitzerlandId),
(UUID(), 'Lauerz', @SwitzerlandId),
(UUID(), 'Morschach', @SwitzerlandId),
(UUID(), 'Muotathal', @SwitzerlandId),
(UUID(), 'Oberiberg', @SwitzerlandId),
(UUID(), 'Riemenstalden', @SwitzerlandId),
(UUID(), 'Rothenthurm', @SwitzerlandId),
(UUID(), 'Sattel', @SwitzerlandId),
(UUID(), 'Schwyz', @SwitzerlandId),
(UUID(), 'Steinen', @SwitzerlandId),
(UUID(), 'Steinerberg', @SwitzerlandId),
(UUID(), 'Unteriberg', @SwitzerlandId),
(UUID(), 'Alpnach', @SwitzerlandId),
(UUID(), 'Engelberg', @SwitzerlandId),
(UUID(), 'Giswil', @SwitzerlandId),
(UUID(), 'Kerns', @SwitzerlandId),
(UUID(), 'Lungern', @SwitzerlandId),
(UUID(), 'Sachseln', @SwitzerlandId),
(UUID(), 'Sarnen', @SwitzerlandId),
(UUID(), 'Beckenried', @SwitzerlandId),
(UUID(), 'Buochs', @SwitzerlandId),
(UUID(), 'Dallenwil', @SwitzerlandId),
(UUID(), 'Emmetten', @SwitzerlandId),
(UUID(), 'Ennetbürgen', @SwitzerlandId),
(UUID(), 'Ennetmoos', @SwitzerlandId),
(UUID(), 'Hergiswil (NW)', @SwitzerlandId),
(UUID(), 'Oberdorf (NW)', @SwitzerlandId),
(UUID(), 'Stans', @SwitzerlandId),
(UUID(), 'Stansstad', @SwitzerlandId),
(UUID(), 'Wolfenschiessen', @SwitzerlandId),
(UUID(), 'Glarus Nord', @SwitzerlandId),
(UUID(), 'Glarus Süd', @SwitzerlandId),
(UUID(), 'Glarus', @SwitzerlandId),
(UUID(), 'Baar', @SwitzerlandId),
(UUID(), 'Cham', @SwitzerlandId),
(UUID(), 'Hünenberg', @SwitzerlandId),
(UUID(), 'Menzingen', @SwitzerlandId),
(UUID(), 'Neuheim', @SwitzerlandId),
(UUID(), 'Oberägeri', @SwitzerlandId),
(UUID(), 'Risch', @SwitzerlandId),
(UUID(), 'Steinhausen', @SwitzerlandId),
(UUID(), 'Unterägeri', @SwitzerlandId),
(UUID(), 'Walchwil', @SwitzerlandId),
(UUID(), 'Zug', @SwitzerlandId),
(UUID(), 'Châtillon (FR)', @SwitzerlandId),
(UUID(), 'Cheiry', @SwitzerlandId),
(UUID(), 'Cugy (FR)', @SwitzerlandId),
(UUID(), 'Fétigny', @SwitzerlandId),
(UUID(), 'Gletterens', @SwitzerlandId),
(UUID(), 'Lully (FR)', @SwitzerlandId),
(UUID(), 'Ménières', @SwitzerlandId),
(UUID(), 'Montagny (FR)', @SwitzerlandId),
(UUID(), 'Nuvilly', @SwitzerlandId),
(UUID(), 'Prévondavaux', @SwitzerlandId),
(UUID(), 'Saint-Aubin (FR)', @SwitzerlandId),
(UUID(), 'Sévaz', @SwitzerlandId),
(UUID(), 'Surpierre', @SwitzerlandId),
(UUID(), 'Vallon', @SwitzerlandId),
(UUID(), 'Les Montets', @SwitzerlandId),
(UUID(), 'Delley-Portalban', @SwitzerlandId),
(UUID(), 'Belmont-Broye', @SwitzerlandId),
(UUID(), 'Estavayer', @SwitzerlandId),
(UUID(), 'Cheyres-Châbles', @SwitzerlandId),
(UUID(), 'Auboranges', @SwitzerlandId),
(UUID(), 'Billens-Hennens', @SwitzerlandId),
(UUID(), 'Chapelle (Glâne)', @SwitzerlandId),
(UUID(), 'Le Châtelard', @SwitzerlandId),
(UUID(), 'Châtonnaye', @SwitzerlandId),
(UUID(), 'Ecublens (FR)', @SwitzerlandId),
(UUID(), 'Grangettes', @SwitzerlandId),
(UUID(), 'Massonnens', @SwitzerlandId),
(UUID(), 'Mézières (FR)', @SwitzerlandId),
(UUID(), 'Montet (Glâne)', @SwitzerlandId),
(UUID(), 'Romont (FR)', @SwitzerlandId),
(UUID(), 'Rue', @SwitzerlandId),
(UUID(), 'Siviriez', @SwitzerlandId),
(UUID(), 'Ursy', @SwitzerlandId),
(UUID(), 'Villaz-Saint-Pierre', @SwitzerlandId),
(UUID(), 'Vuisternens-devant-Romont', @SwitzerlandId),
(UUID(), 'Villorsonnens', @SwitzerlandId),
(UUID(), 'Torny', @SwitzerlandId),
(UUID(), 'La Folliaz', @SwitzerlandId),
(UUID(), 'Haut-Intyamon', @SwitzerlandId),
(UUID(), 'Pont-en-Ogoz', @SwitzerlandId),
(UUID(), 'Botterens', @SwitzerlandId),
(UUID(), 'Broc', @SwitzerlandId),
(UUID(), 'Bulle', @SwitzerlandId),
(UUID(), 'Châtel-sur-Montsalvens', @SwitzerlandId),
(UUID(), 'Corbières', @SwitzerlandId),
(UUID(), 'Crésuz', @SwitzerlandId),
(UUID(), 'Echarlens', @SwitzerlandId),
(UUID(), 'Grandvillard', @SwitzerlandId),
(UUID(), 'Gruyères', @SwitzerlandId),
(UUID(), 'Hauteville', @SwitzerlandId),
(UUID(), 'Jaun', @SwitzerlandId),
(UUID(), 'Marsens', @SwitzerlandId),
(UUID(), 'Morlon', @SwitzerlandId),
(UUID(), 'Le Pâquier (FR)', @SwitzerlandId),
(UUID(), 'Pont-la-Ville', @SwitzerlandId),
(UUID(), 'Riaz', @SwitzerlandId),
(UUID(), 'La Roche', @SwitzerlandId),
(UUID(), 'Sâles', @SwitzerlandId),
(UUID(), 'Sorens', @SwitzerlandId),
(UUID(), 'Vaulruz', @SwitzerlandId),
(UUID(), 'Vuadens', @SwitzerlandId),
(UUID(), 'Bas-Intyamon', @SwitzerlandId),
(UUID(), 'Val-de-Charmey', @SwitzerlandId),
(UUID(), 'Arconciel', @SwitzerlandId),
(UUID(), 'Autigny', @SwitzerlandId),
(UUID(), 'Avry', @SwitzerlandId),
(UUID(), 'Belfaux', @SwitzerlandId),
(UUID(), 'Chénens', @SwitzerlandId),
(UUID(), 'Corminboeuf', @SwitzerlandId),
(UUID(), 'Corserey', @SwitzerlandId),
(UUID(), 'Cottens (FR)', @SwitzerlandId),
(UUID(), 'Ependes (FR)', @SwitzerlandId),
(UUID(), 'Ferpicloz', @SwitzerlandId),
(UUID(), 'Fribourg', @SwitzerlandId),
(UUID(), 'Givisiez', @SwitzerlandId),
(UUID(), 'Granges-Paccot', @SwitzerlandId),
(UUID(), 'Grolley', @SwitzerlandId),
(UUID(), 'Marly', @SwitzerlandId),
(UUID(), 'Matran', @SwitzerlandId),
(UUID(), 'Neyruz (FR)', @SwitzerlandId),
(UUID(), 'Noréaz', @SwitzerlandId),
(UUID(), 'Pierrafortscha', @SwitzerlandId),
(UUID(), 'Ponthaux', @SwitzerlandId),
(UUID(), 'Le Mouret', @SwitzerlandId),
(UUID(), 'Prez-vers-Noréaz', @SwitzerlandId),
(UUID(), 'Senèdes', @SwitzerlandId),
(UUID(), 'Treyvaux', @SwitzerlandId),
(UUID(), 'Villars-sur-Glâne', @SwitzerlandId),
(UUID(), 'Villarsel-sur-Marly', @SwitzerlandId),
(UUID(), 'Hauterive (FR)', @SwitzerlandId),
(UUID(), 'La Brillaz', @SwitzerlandId),
(UUID(), 'La Sonnaz', @SwitzerlandId),
(UUID(), 'Gibloux', @SwitzerlandId),
(UUID(), 'Courgevaux', @SwitzerlandId),
(UUID(), 'Courtepin', @SwitzerlandId),
(UUID(), 'Cressier (FR)', @SwitzerlandId),
(UUID(), 'Fräschels', @SwitzerlandId),
(UUID(), 'Galmiz', @SwitzerlandId),
(UUID(), 'Gempenach', @SwitzerlandId),
(UUID(), 'Greng', @SwitzerlandId),
(UUID(), 'Gurmels', @SwitzerlandId),
(UUID(), 'Kerzers', @SwitzerlandId),
(UUID(), 'Kleinbösingen', @SwitzerlandId),
(UUID(), 'Meyriez', @SwitzerlandId),
(UUID(), 'Misery-Courtion', @SwitzerlandId),
(UUID(), 'Muntelier', @SwitzerlandId),
(UUID(), 'Murten', @SwitzerlandId),
(UUID(), 'Ried bei Kerzers', @SwitzerlandId),
(UUID(), 'Ulmiz', @SwitzerlandId),
(UUID(), 'Mont-Vully', @SwitzerlandId),
(UUID(), 'Alterswil', @SwitzerlandId),
(UUID(), 'Brünisried', @SwitzerlandId),
(UUID(), 'Düdingen', @SwitzerlandId),
(UUID(), 'Giffers', @SwitzerlandId),
(UUID(), 'Bösingen', @SwitzerlandId),
(UUID(), 'Heitenried', @SwitzerlandId),
(UUID(), 'Plaffeien', @SwitzerlandId),
(UUID(), 'Plasselb', @SwitzerlandId),
(UUID(), 'Rechthalten', @SwitzerlandId),
(UUID(), 'St. Antoni', @SwitzerlandId),
(UUID(), 'St. Silvester', @SwitzerlandId),
(UUID(), 'St. Ursen', @SwitzerlandId),
(UUID(), 'Schmitten (FR)', @SwitzerlandId),
(UUID(), 'Tafers', @SwitzerlandId),
(UUID(), 'Tentlingen', @SwitzerlandId),
(UUID(), 'Ueberstorf', @SwitzerlandId),
(UUID(), 'Wünnewil-Flamatt', @SwitzerlandId),
(UUID(), 'Attalens', @SwitzerlandId),
(UUID(), 'Bossonnens', @SwitzerlandId),
(UUID(), 'Châtel-Saint-Denis', @SwitzerlandId),
(UUID(), 'Granges (Veveyse)', @SwitzerlandId),
(UUID(), 'Remaufens', @SwitzerlandId),
(UUID(), 'Saint-Martin (FR)', @SwitzerlandId),
(UUID(), 'Semsales', @SwitzerlandId),
(UUID(), 'Le Flon', @SwitzerlandId),
(UUID(), 'La Verrerie', @SwitzerlandId),
(UUID(), 'Staatswald Galm', @SwitzerlandId),
(UUID(), 'Egerkingen', @SwitzerlandId),
(UUID(), 'Härkingen', @SwitzerlandId),
(UUID(), 'Kestenholz', @SwitzerlandId),
(UUID(), 'Neuendorf', @SwitzerlandId),
(UUID(), 'Niederbuchsiten', @SwitzerlandId),
(UUID(), 'Oberbuchsiten', @SwitzerlandId),
(UUID(), 'Oensingen', @SwitzerlandId),
(UUID(), 'Wolfwil', @SwitzerlandId),
(UUID(), 'Aedermannsdorf', @SwitzerlandId),
(UUID(), 'Balsthal', @SwitzerlandId),
(UUID(), 'Gänsbrunnen', @SwitzerlandId),
(UUID(), 'Herbetswil', @SwitzerlandId),
(UUID(), 'Holderbank (SO)', @SwitzerlandId),
(UUID(), 'Laupersdorf', @SwitzerlandId),
(UUID(), 'Matzendorf', @SwitzerlandId),
(UUID(), 'Mümliswil-Ramiswil', @SwitzerlandId),
(UUID(), 'Welschenrohr', @SwitzerlandId),
(UUID(), 'Biezwil', @SwitzerlandId),
(UUID(), 'Lüterkofen-Ichertswil', @SwitzerlandId),
(UUID(), 'Lüterswil-Gächliwil', @SwitzerlandId),
(UUID(), 'Messen', @SwitzerlandId),
(UUID(), 'Schnottwil', @SwitzerlandId),
(UUID(), 'Unterramsern', @SwitzerlandId),
(UUID(), 'Lüsslingen-Nennigkofen', @SwitzerlandId),
(UUID(), 'Buchegg', @SwitzerlandId),
(UUID(), 'Bättwil', @SwitzerlandId),
(UUID(), 'Büren (SO)', @SwitzerlandId),
(UUID(), 'Dornach', @SwitzerlandId),
(UUID(), 'Gempen', @SwitzerlandId),
(UUID(), 'Hochwald', @SwitzerlandId),
(UUID(), 'Hofstetten-Flüh', @SwitzerlandId),
(UUID(), 'Metzerlen-Mariastein', @SwitzerlandId),
(UUID(), 'Nuglar-St. Pantaleon', @SwitzerlandId),
(UUID(), 'Rodersdorf', @SwitzerlandId),
(UUID(), 'Seewen', @SwitzerlandId),
(UUID(), 'Witterswil', @SwitzerlandId),
(UUID(), 'Hauenstein-Ifenthal', @SwitzerlandId),
(UUID(), 'Kienberg', @SwitzerlandId),
(UUID(), 'Lostorf', @SwitzerlandId),
(UUID(), 'Niedergösgen', @SwitzerlandId),
(UUID(), 'Obergösgen', @SwitzerlandId),
(UUID(), 'Rohr (SO)', @SwitzerlandId),
(UUID(), 'Stüsslingen', @SwitzerlandId),
(UUID(), 'Trimbach', @SwitzerlandId),
(UUID(), 'Winznau', @SwitzerlandId),
(UUID(), 'Wisen (SO)', @SwitzerlandId),
(UUID(), 'Erlinsbach (SO)', @SwitzerlandId),
(UUID(), 'Aeschi (SO)', @SwitzerlandId),
(UUID(), 'Biberist', @SwitzerlandId),
(UUID(), 'Bolken', @SwitzerlandId),
(UUID(), 'Deitingen', @SwitzerlandId),
(UUID(), 'Derendingen', @SwitzerlandId),
(UUID(), 'Etziken', @SwitzerlandId),
(UUID(), 'Gerlafingen', @SwitzerlandId),
(UUID(), 'Halten', @SwitzerlandId),
(UUID(), 'Horriwil', @SwitzerlandId),
(UUID(), 'Hüniken', @SwitzerlandId),
(UUID(), 'Kriegstetten', @SwitzerlandId),
(UUID(), 'Lohn-Ammannsegg', @SwitzerlandId),
(UUID(), 'Luterbach', @SwitzerlandId),
(UUID(), 'Obergerlafingen', @SwitzerlandId),
(UUID(), 'Oekingen', @SwitzerlandId),
(UUID(), 'Recherswil', @SwitzerlandId),
(UUID(), 'Subingen', @SwitzerlandId),
(UUID(), 'Zuchwil', @SwitzerlandId),
(UUID(), 'Drei Höfe', @SwitzerlandId),
(UUID(), 'Balm bei Günsberg', @SwitzerlandId),
(UUID(), 'Bellach', @SwitzerlandId),
(UUID(), 'Bettlach', @SwitzerlandId),
(UUID(), 'Feldbrunnen-St. Niklaus', @SwitzerlandId),
(UUID(), 'Flumenthal', @SwitzerlandId),
(UUID(), 'Grenchen', @SwitzerlandId),
(UUID(), 'Günsberg', @SwitzerlandId),
(UUID(), 'Hubersdorf', @SwitzerlandId),
(UUID(), 'Kammersrohr', @SwitzerlandId),
(UUID(), 'Langendorf', @SwitzerlandId),
(UUID(), 'Lommiswil', @SwitzerlandId),
(UUID(), 'Oberdorf (SO)', @SwitzerlandId),
(UUID(), 'Riedholz', @SwitzerlandId),
(UUID(), 'Rüttenen', @SwitzerlandId),
(UUID(), 'Selzach', @SwitzerlandId),
(UUID(), 'Boningen', @SwitzerlandId),
(UUID(), 'Däniken', @SwitzerlandId),
(UUID(), 'Dulliken', @SwitzerlandId),
(UUID(), 'Eppenberg-Wöschnau', @SwitzerlandId),
(UUID(), 'Fulenbach', @SwitzerlandId),
(UUID(), 'Gretzenbach', @SwitzerlandId),
(UUID(), 'Gunzgen', @SwitzerlandId),
(UUID(), 'Hägendorf', @SwitzerlandId),
(UUID(), 'Kappel (SO)', @SwitzerlandId),
(UUID(), 'Olten', @SwitzerlandId),
(UUID(), 'Rickenbach (SO)', @SwitzerlandId),
(UUID(), 'Schönenwerd', @SwitzerlandId),
(UUID(), 'Starrkirch-Wil', @SwitzerlandId),
(UUID(), 'Walterswil (SO)', @SwitzerlandId),
(UUID(), 'Wangen bei Olten', @SwitzerlandId),
(UUID(), 'Solothurn', @SwitzerlandId),
(UUID(), 'Bärschwil', @SwitzerlandId),
(UUID(), 'Beinwil (SO)', @SwitzerlandId),
(UUID(), 'Breitenbach', @SwitzerlandId),
(UUID(), 'Büsserach', @SwitzerlandId),
(UUID(), 'Erschwil', @SwitzerlandId),
(UUID(), 'Fehren', @SwitzerlandId),
(UUID(), 'Grindel', @SwitzerlandId),
(UUID(), 'Himmelried', @SwitzerlandId),
(UUID(), 'Kleinlützel', @SwitzerlandId),
(UUID(), 'Meltingen', @SwitzerlandId),
(UUID(), 'Nunningen', @SwitzerlandId),
(UUID(), 'Zullwil', @SwitzerlandId),
(UUID(), 'Basel', @SwitzerlandId),
(UUID(), 'Bettingen', @SwitzerlandId),
(UUID(), 'Riehen', @SwitzerlandId),
(UUID(), 'Aesch (BL)', @SwitzerlandId),
(UUID(), 'Allschwil', @SwitzerlandId),
(UUID(), 'Arlesheim', @SwitzerlandId),
(UUID(), 'Biel-Benken', @SwitzerlandId),
(UUID(), 'Binningen', @SwitzerlandId),
(UUID(), 'Birsfelden', @SwitzerlandId),
(UUID(), 'Bottmingen', @SwitzerlandId),
(UUID(), 'Ettingen', @SwitzerlandId),
(UUID(), 'Münchenstein', @SwitzerlandId),
(UUID(), 'Muttenz', @SwitzerlandId),
(UUID(), 'Oberwil (BL)', @SwitzerlandId),
(UUID(), 'Pfeffingen', @SwitzerlandId),
(UUID(), 'Reinach (BL)', @SwitzerlandId),
(UUID(), 'Schönenbuch', @SwitzerlandId),
(UUID(), 'Therwil', @SwitzerlandId),
(UUID(), 'Blauen', @SwitzerlandId),
(UUID(), 'Brislach', @SwitzerlandId),
(UUID(), 'Burg im Leimental', @SwitzerlandId),
(UUID(), 'Dittingen', @SwitzerlandId),
(UUID(), 'Duggingen', @SwitzerlandId),
(UUID(), 'Grellingen', @SwitzerlandId),
(UUID(), 'Laufen', @SwitzerlandId),
(UUID(), 'Liesberg', @SwitzerlandId),
(UUID(), 'Nenzlingen', @SwitzerlandId),
(UUID(), 'Roggenburg', @SwitzerlandId),
(UUID(), 'Röschenz', @SwitzerlandId),
(UUID(), 'Wahlen', @SwitzerlandId),
(UUID(), 'Zwingen', @SwitzerlandId),
(UUID(), 'Arisdorf', @SwitzerlandId),
(UUID(), 'Augst', @SwitzerlandId),
(UUID(), 'Bubendorf', @SwitzerlandId),
(UUID(), 'Frenkendorf', @SwitzerlandId),
(UUID(), 'Füllinsdorf', @SwitzerlandId),
(UUID(), 'Giebenach', @SwitzerlandId),
(UUID(), 'Hersberg', @SwitzerlandId),
(UUID(), 'Lausen', @SwitzerlandId),
(UUID(), 'Liestal', @SwitzerlandId),
(UUID(), 'Lupsingen', @SwitzerlandId),
(UUID(), 'Pratteln', @SwitzerlandId),
(UUID(), 'Ramlinsburg', @SwitzerlandId),
(UUID(), 'Seltisberg', @SwitzerlandId),
(UUID(), 'Ziefen', @SwitzerlandId),
(UUID(), 'Anwil', @SwitzerlandId),
(UUID(), 'Böckten', @SwitzerlandId),
(UUID(), 'Buckten', @SwitzerlandId),
(UUID(), 'Buus', @SwitzerlandId),
(UUID(), 'Diepflingen', @SwitzerlandId),
(UUID(), 'Gelterkinden', @SwitzerlandId),
(UUID(), 'Häfelfingen', @SwitzerlandId),
(UUID(), 'Hemmiken', @SwitzerlandId),
(UUID(), 'Itingen', @SwitzerlandId),
(UUID(), 'Känerkinden', @SwitzerlandId),
(UUID(), 'Kilchberg (BL)', @SwitzerlandId),
(UUID(), 'Läufelfingen', @SwitzerlandId),
(UUID(), 'Maisprach', @SwitzerlandId),
(UUID(), 'Nusshof', @SwitzerlandId),
(UUID(), 'Oltingen', @SwitzerlandId),
(UUID(), 'Ormalingen', @SwitzerlandId),
(UUID(), 'Rickenbach (BL)', @SwitzerlandId),
(UUID(), 'Rothenfluh', @SwitzerlandId),
(UUID(), 'Rümlingen', @SwitzerlandId),
(UUID(), 'Rünenberg', @SwitzerlandId),
(UUID(), 'Sissach', @SwitzerlandId),
(UUID(), 'Tecknau', @SwitzerlandId),
(UUID(), 'Tenniken', @SwitzerlandId),
(UUID(), 'Thürnen', @SwitzerlandId),
(UUID(), 'Wenslingen', @SwitzerlandId),
(UUID(), 'Wintersingen', @SwitzerlandId),
(UUID(), 'Wittinsburg', @SwitzerlandId),
(UUID(), 'Zeglingen', @SwitzerlandId),
(UUID(), 'Zunzgen', @SwitzerlandId),
(UUID(), 'Arboldswil', @SwitzerlandId),
(UUID(), 'Bennwil', @SwitzerlandId),
(UUID(), 'Bretzwil', @SwitzerlandId),
(UUID(), 'Diegten', @SwitzerlandId),
(UUID(), 'Eptingen', @SwitzerlandId),
(UUID(), 'Hölstein', @SwitzerlandId),
(UUID(), 'Lampenberg', @SwitzerlandId),
(UUID(), 'Langenbruck', @SwitzerlandId),
(UUID(), 'Lauwil', @SwitzerlandId),
(UUID(), 'Liedertswil', @SwitzerlandId),
(UUID(), 'Niederdorf', @SwitzerlandId),
(UUID(), 'Oberdorf (BL)', @SwitzerlandId),
(UUID(), 'Reigoldswil', @SwitzerlandId),
(UUID(), 'Titterten', @SwitzerlandId),
(UUID(), 'Waldenburg', @SwitzerlandId),
(UUID(), 'Gächlingen', @SwitzerlandId),
(UUID(), 'Löhningen', @SwitzerlandId),
(UUID(), 'Neunkirch', @SwitzerlandId),
(UUID(), 'Büttenhardt', @SwitzerlandId),
(UUID(), 'Dörflingen', @SwitzerlandId),
(UUID(), 'Lohn (SH)', @SwitzerlandId),
(UUID(), 'Stetten (SH)', @SwitzerlandId),
(UUID(), 'Thayngen', @SwitzerlandId),
(UUID(), 'Bargen (SH)', @SwitzerlandId),
(UUID(), 'Beringen', @SwitzerlandId),
(UUID(), 'Buchberg', @SwitzerlandId),
(UUID(), 'Merishausen', @SwitzerlandId),
(UUID(), 'Neuhausen am Rheinfall', @SwitzerlandId),
(UUID(), 'Rüdlingen', @SwitzerlandId),
(UUID(), 'Schaffhausen', @SwitzerlandId),
(UUID(), 'Beggingen', @SwitzerlandId),
(UUID(), 'Schleitheim', @SwitzerlandId),
(UUID(), 'Siblingen', @SwitzerlandId),
(UUID(), 'Buch (SH)', @SwitzerlandId),
(UUID(), 'Hemishofen', @SwitzerlandId),
(UUID(), 'Ramsen', @SwitzerlandId),
(UUID(), 'Stein am Rhein', @SwitzerlandId),
(UUID(), 'Hallau', @SwitzerlandId),
(UUID(), 'Oberhallau', @SwitzerlandId),
(UUID(), 'Trasadingen', @SwitzerlandId),
(UUID(), 'Wilchingen', @SwitzerlandId),
(UUID(), 'Herisau', @SwitzerlandId),
(UUID(), 'Hundwil', @SwitzerlandId),
(UUID(), 'Schönengrund', @SwitzerlandId),
(UUID(), 'Schwellbrunn', @SwitzerlandId),
(UUID(), 'Stein (AR)', @SwitzerlandId),
(UUID(), 'Urnäsch', @SwitzerlandId),
(UUID(), 'Waldstatt', @SwitzerlandId),
(UUID(), 'Bühler', @SwitzerlandId),
(UUID(), 'Gais', @SwitzerlandId),
(UUID(), 'Speicher', @SwitzerlandId),
(UUID(), 'Teufen (AR)', @SwitzerlandId),
(UUID(), 'Trogen', @SwitzerlandId),
(UUID(), 'Grub (AR)', @SwitzerlandId),
(UUID(), 'Heiden', @SwitzerlandId),
(UUID(), 'Lutzenberg', @SwitzerlandId),
(UUID(), 'Rehetobel', @SwitzerlandId),
(UUID(), 'Reute (AR)', @SwitzerlandId),
(UUID(), 'Wald (AR)', @SwitzerlandId),
(UUID(), 'Walzenhausen', @SwitzerlandId),
(UUID(), 'Wolfhalden', @SwitzerlandId),
(UUID(), 'Appenzell', @SwitzerlandId),
(UUID(), 'Gonten', @SwitzerlandId),
(UUID(), 'Rüte', @SwitzerlandId),
(UUID(), 'Schlatt-Haslen', @SwitzerlandId),
(UUID(), 'Schwende', @SwitzerlandId),
(UUID(), 'Oberegg', @SwitzerlandId),
(UUID(), 'Häggenschwil', @SwitzerlandId),
(UUID(), 'Muolen', @SwitzerlandId),
(UUID(), 'St. Gallen', @SwitzerlandId),
(UUID(), 'Wittenbach', @SwitzerlandId),
(UUID(), 'Berg (SG)', @SwitzerlandId),
(UUID(), 'Eggersriet', @SwitzerlandId),
(UUID(), 'Goldach', @SwitzerlandId),
(UUID(), 'Mörschwil', @SwitzerlandId),
(UUID(), 'Rorschach', @SwitzerlandId),
(UUID(), 'Rorschacherberg', @SwitzerlandId),
(UUID(), 'Steinach', @SwitzerlandId),
(UUID(), 'Tübach', @SwitzerlandId),
(UUID(), 'Untereggen', @SwitzerlandId),
(UUID(), 'Au (SG)', @SwitzerlandId),
(UUID(), 'Balgach', @SwitzerlandId),
(UUID(), 'Berneck', @SwitzerlandId),
(UUID(), 'Diepoldsau', @SwitzerlandId),
(UUID(), 'Rheineck', @SwitzerlandId),
(UUID(), 'St. Margrethen', @SwitzerlandId),
(UUID(), 'Thal', @SwitzerlandId),
(UUID(), 'Widnau', @SwitzerlandId),
(UUID(), 'Altstätten', @SwitzerlandId),
(UUID(), 'Eichberg', @SwitzerlandId),
(UUID(), 'Marbach (SG)', @SwitzerlandId),
(UUID(), 'Oberriet (SG)', @SwitzerlandId),
(UUID(), 'Rebstein', @SwitzerlandId),
(UUID(), 'Rüthi (SG)', @SwitzerlandId),
(UUID(), 'Buchs (SG)', @SwitzerlandId),
(UUID(), 'Gams', @SwitzerlandId),
(UUID(), 'Grabs', @SwitzerlandId),
(UUID(), 'Sennwald', @SwitzerlandId),
(UUID(), 'Sevelen', @SwitzerlandId),
(UUID(), 'Wartau', @SwitzerlandId),
(UUID(), 'Bad Ragaz', @SwitzerlandId),
(UUID(), 'Flums', @SwitzerlandId),
(UUID(), 'Mels', @SwitzerlandId),
(UUID(), 'Pfäfers', @SwitzerlandId),
(UUID(), 'Quarten', @SwitzerlandId),
(UUID(), 'Sargans', @SwitzerlandId),
(UUID(), 'Vilters-Wangs', @SwitzerlandId),
(UUID(), 'Walenstadt', @SwitzerlandId),
(UUID(), 'Amden', @SwitzerlandId),
(UUID(), 'Benken (SG)', @SwitzerlandId),
(UUID(), 'Kaltbrunn', @SwitzerlandId),
(UUID(), 'Schänis', @SwitzerlandId),
(UUID(), 'Weesen', @SwitzerlandId),
(UUID(), 'Schmerikon', @SwitzerlandId),
(UUID(), 'Uznach', @SwitzerlandId),
(UUID(), 'Rapperswil-Jona', @SwitzerlandId),
(UUID(), 'Gommiswald', @SwitzerlandId),
(UUID(), 'Eschenbach (SG)', @SwitzerlandId),
(UUID(), 'Ebnat-Kappel', @SwitzerlandId),
(UUID(), 'Wildhaus-Alt St. Johann', @SwitzerlandId),
(UUID(), 'Nesslau', @SwitzerlandId),
(UUID(), 'Hemberg', @SwitzerlandId),
(UUID(), 'Lichtensteig', @SwitzerlandId),
(UUID(), 'Oberhelfenschwil', @SwitzerlandId),
(UUID(), 'Neckertal', @SwitzerlandId),
(UUID(), 'Wattwil', @SwitzerlandId),
(UUID(), 'Kirchberg (SG)', @SwitzerlandId),
(UUID(), 'Lütisburg', @SwitzerlandId),
(UUID(), 'Mosnang', @SwitzerlandId),
(UUID(), 'Bütschwil-Ganterschwil', @SwitzerlandId),
(UUID(), 'Degersheim', @SwitzerlandId),
(UUID(), 'Flawil', @SwitzerlandId),
(UUID(), 'Jonschwil', @SwitzerlandId),
(UUID(), 'Oberuzwil', @SwitzerlandId),
(UUID(), 'Uzwil', @SwitzerlandId),
(UUID(), 'Niederbüren', @SwitzerlandId),
(UUID(), 'Niederhelfenschwil', @SwitzerlandId),
(UUID(), 'Oberbüren', @SwitzerlandId),
(UUID(), 'Zuzwil (SG)', @SwitzerlandId),
(UUID(), 'Wil (SG)', @SwitzerlandId),
(UUID(), 'Andwil (SG)', @SwitzerlandId),
(UUID(), 'Gaiserwald', @SwitzerlandId),
(UUID(), 'Gossau (SG)', @SwitzerlandId),
(UUID(), 'Waldkirch', @SwitzerlandId),
(UUID(), 'Vaz/Obervaz', @SwitzerlandId),
(UUID(), 'Lantsch/Lenz', @SwitzerlandId),
(UUID(), 'Schmitten (GR)', @SwitzerlandId),
(UUID(), 'Albula/Alvra', @SwitzerlandId),
(UUID(), 'Surses', @SwitzerlandId),
(UUID(), 'Bergün Filisur', @SwitzerlandId),
(UUID(), 'Brusio', @SwitzerlandId),
(UUID(), 'Poschiavo', @SwitzerlandId),
(UUID(), 'Falera', @SwitzerlandId),
(UUID(), 'Laax', @SwitzerlandId),
(UUID(), 'Sagogn', @SwitzerlandId),
(UUID(), 'Schluein', @SwitzerlandId),
(UUID(), 'Vals', @SwitzerlandId),
(UUID(), 'Lumnezia', @SwitzerlandId),
(UUID(), 'Ilanz/Glion', @SwitzerlandId),
(UUID(), 'Fürstenau', @SwitzerlandId),
(UUID(), 'Rothenbrunnen', @SwitzerlandId),
(UUID(), 'Scharans', @SwitzerlandId),
(UUID(), 'Sils im Domleschg', @SwitzerlandId),
(UUID(), 'Cazis', @SwitzerlandId),
(UUID(), 'Flerden', @SwitzerlandId),
(UUID(), 'Masein', @SwitzerlandId),
(UUID(), 'Thusis', @SwitzerlandId),
(UUID(), 'Tschappina', @SwitzerlandId),
(UUID(), 'Urmein', @SwitzerlandId),
(UUID(), 'Safiental', @SwitzerlandId),
(UUID(), 'Domleschg', @SwitzerlandId),
(UUID(), 'Avers', @SwitzerlandId),
(UUID(), 'Sufers', @SwitzerlandId),
(UUID(), 'Andeer', @SwitzerlandId),
(UUID(), 'Casti-Wergenstein', @SwitzerlandId),
(UUID(), 'Donat', @SwitzerlandId),
(UUID(), 'Lohn (GR)', @SwitzerlandId),
(UUID(), 'Mathon', @SwitzerlandId),
(UUID(), 'Rongellen', @SwitzerlandId),
(UUID(), 'Zillis-Reischen', @SwitzerlandId),
(UUID(), 'Ferrera', @SwitzerlandId),
(UUID(), 'Rheinwald', @SwitzerlandId),
(UUID(), 'Bonaduz', @SwitzerlandId),
(UUID(), 'Domat/Ems', @SwitzerlandId),
(UUID(), 'Rhäzüns', @SwitzerlandId),
(UUID(), 'Felsberg', @SwitzerlandId),
(UUID(), 'Flims', @SwitzerlandId),
(UUID(), 'Tamins', @SwitzerlandId),
(UUID(), 'Trin', @SwitzerlandId),
(UUID(), 'Zernez', @SwitzerlandId),
(UUID(), 'Samnaun', @SwitzerlandId),
(UUID(), 'Scuol', @SwitzerlandId),
(UUID(), 'Valsot', @SwitzerlandId),
(UUID(), 'Bever', @SwitzerlandId),
(UUID(), 'Celerina/Schlarigna', @SwitzerlandId),
(UUID(), 'Madulain', @SwitzerlandId),
(UUID(), 'Pontresina', @SwitzerlandId),
(UUID(), 'La Punt-Chamues-ch', @SwitzerlandId),
(UUID(), 'Samedan', @SwitzerlandId),
(UUID(), 'St. Moritz', @SwitzerlandId),
(UUID(), 'S-chanf', @SwitzerlandId),
(UUID(), 'Sils im Engadin/Segl', @SwitzerlandId),
(UUID(), 'Silvaplana', @SwitzerlandId),
(UUID(), 'Zuoz', @SwitzerlandId),
(UUID(), 'Bregaglia', @SwitzerlandId),
(UUID(), 'Buseno', @SwitzerlandId),
(UUID(), 'Castaneda', @SwitzerlandId),
(UUID(), 'Rossa', @SwitzerlandId),
(UUID(), 'Santa Maria in Calanca', @SwitzerlandId),
(UUID(), 'Lostallo', @SwitzerlandId),
(UUID(), 'Mesocco', @SwitzerlandId),
(UUID(), 'Soazza', @SwitzerlandId),
(UUID(), 'Cama', @SwitzerlandId),
(UUID(), 'Grono', @SwitzerlandId),
(UUID(), 'Roveredo (GR)', @SwitzerlandId),
(UUID(), 'San Vittore', @SwitzerlandId),
(UUID(), 'Calanca', @SwitzerlandId),
(UUID(), 'Val Müstair', @SwitzerlandId),
(UUID(), 'Davos', @SwitzerlandId),
(UUID(), 'Fideris', @SwitzerlandId),
(UUID(), 'Furna', @SwitzerlandId),
(UUID(), 'Jenaz', @SwitzerlandId),
(UUID(), 'Klosters-Serneus', @SwitzerlandId),
(UUID(), 'Conters im Prättigau', @SwitzerlandId),
(UUID(), 'Küblis', @SwitzerlandId),
(UUID(), 'Luzein', @SwitzerlandId),
(UUID(), 'Chur', @SwitzerlandId),
(UUID(), 'Churwalden', @SwitzerlandId),
(UUID(), 'Arosa', @SwitzerlandId),
(UUID(), 'Maladers', @SwitzerlandId),
(UUID(), 'Tschiertschen-Praden', @SwitzerlandId),
(UUID(), 'Haldenstein', @SwitzerlandId),
(UUID(), 'Trimmis', @SwitzerlandId),
(UUID(), 'Untervaz', @SwitzerlandId),
(UUID(), 'Zizers', @SwitzerlandId),
(UUID(), 'Fläsch', @SwitzerlandId),
(UUID(), 'Jenins', @SwitzerlandId),
(UUID(), 'Maienfeld', @SwitzerlandId),
(UUID(), 'Malans', @SwitzerlandId),
(UUID(), 'Landquart', @SwitzerlandId),
(UUID(), 'Grüsch', @SwitzerlandId),
(UUID(), 'Schiers', @SwitzerlandId),
(UUID(), 'Seewis im Prättigau', @SwitzerlandId),
(UUID(), 'Breil/Brigels', @SwitzerlandId),
(UUID(), 'Disentis/Mustér', @SwitzerlandId),
(UUID(), 'Medel (Lucmagn)', @SwitzerlandId),
(UUID(), 'Sumvitg', @SwitzerlandId),
(UUID(), 'Tujetsch', @SwitzerlandId),
(UUID(), 'Trun', @SwitzerlandId),
(UUID(), 'Obersaxen Mundaun', @SwitzerlandId),
(UUID(), 'Aarau', @SwitzerlandId),
(UUID(), 'Biberstein', @SwitzerlandId),
(UUID(), 'Buchs (AG)', @SwitzerlandId),
(UUID(), 'Densbüren', @SwitzerlandId),
(UUID(), 'Erlinsbach (AG)', @SwitzerlandId),
(UUID(), 'Gränichen', @SwitzerlandId),
(UUID(), 'Hirschthal', @SwitzerlandId),
(UUID(), 'Küttigen', @SwitzerlandId),
(UUID(), 'Muhen', @SwitzerlandId),
(UUID(), 'Oberentfelden', @SwitzerlandId),
(UUID(), 'Suhr', @SwitzerlandId),
(UUID(), 'Unterentfelden', @SwitzerlandId),
(UUID(), 'Baden', @SwitzerlandId),
(UUID(), 'Bellikon', @SwitzerlandId),
(UUID(), 'Bergdietikon', @SwitzerlandId),
(UUID(), 'Birmenstorf (AG)', @SwitzerlandId),
(UUID(), 'Ennetbaden', @SwitzerlandId),
(UUID(), 'Fislisbach', @SwitzerlandId),
(UUID(), 'Freienwil', @SwitzerlandId),
(UUID(), 'Gebenstorf', @SwitzerlandId),
(UUID(), 'Killwangen', @SwitzerlandId),
(UUID(), 'Künten', @SwitzerlandId),
(UUID(), 'Mägenwil', @SwitzerlandId),
(UUID(), 'Mellingen', @SwitzerlandId),
(UUID(), 'Neuenhof', @SwitzerlandId),
(UUID(), 'Niederrohrdorf', @SwitzerlandId),
(UUID(), 'Oberrohrdorf', @SwitzerlandId),
(UUID(), 'Obersiggenthal', @SwitzerlandId),
(UUID(), 'Remetschwil', @SwitzerlandId),
(UUID(), 'Spreitenbach', @SwitzerlandId),
(UUID(), 'Stetten (AG)', @SwitzerlandId),
(UUID(), 'Turgi', @SwitzerlandId),
(UUID(), 'Untersiggenthal', @SwitzerlandId),
(UUID(), 'Wettingen', @SwitzerlandId),
(UUID(), 'Wohlenschwil', @SwitzerlandId),
(UUID(), 'Würenlingen', @SwitzerlandId),
(UUID(), 'Würenlos', @SwitzerlandId),
(UUID(), 'Ehrendingen', @SwitzerlandId),
(UUID(), 'Arni (AG)', @SwitzerlandId),
(UUID(), 'Berikon', @SwitzerlandId),
(UUID(), 'Bremgarten (AG)', @SwitzerlandId),
(UUID(), 'Büttikon', @SwitzerlandId),
(UUID(), 'Dottikon', @SwitzerlandId),
(UUID(), 'Eggenwil', @SwitzerlandId),
(UUID(), 'Fischbach-Göslikon', @SwitzerlandId),
(UUID(), 'Hägglingen', @SwitzerlandId),
(UUID(), 'Jonen', @SwitzerlandId),
(UUID(), 'Niederwil (AG)', @SwitzerlandId),
(UUID(), 'Oberlunkhofen', @SwitzerlandId),
(UUID(), 'Oberwil-Lieli', @SwitzerlandId),
(UUID(), 'Rudolfstetten-Friedlisberg', @SwitzerlandId),
(UUID(), 'Sarmenstorf', @SwitzerlandId),
(UUID(), 'Tägerig', @SwitzerlandId),
(UUID(), 'Uezwil', @SwitzerlandId),
(UUID(), 'Unterlunkhofen', @SwitzerlandId),
(UUID(), 'Villmergen', @SwitzerlandId),
(UUID(), 'Widen', @SwitzerlandId),
(UUID(), 'Wohlen (AG)', @SwitzerlandId),
(UUID(), 'Zufikon', @SwitzerlandId),
(UUID(), 'Islisberg', @SwitzerlandId),
(UUID(), 'Auenstein', @SwitzerlandId),
(UUID(), 'Birr', @SwitzerlandId),
(UUID(), 'Birrhard', @SwitzerlandId),
(UUID(), 'Bözen', @SwitzerlandId),
(UUID(), 'Brugg', @SwitzerlandId),
(UUID(), 'Effingen', @SwitzerlandId),
(UUID(), 'Elfingen', @SwitzerlandId),
(UUID(), 'Habsburg', @SwitzerlandId),
(UUID(), 'Hausen (AG)', @SwitzerlandId),
(UUID(), 'Lupfig', @SwitzerlandId),
(UUID(), 'Mandach', @SwitzerlandId),
(UUID(), 'Mönthal', @SwitzerlandId),
(UUID(), 'Mülligen', @SwitzerlandId),
(UUID(), 'Remigen', @SwitzerlandId),
(UUID(), 'Riniken', @SwitzerlandId),
(UUID(), 'Rüfenach', @SwitzerlandId),
(UUID(), 'Schinznach-Bad', @SwitzerlandId),
(UUID(), 'Thalheim (AG)', @SwitzerlandId),
(UUID(), 'Veltheim (AG)', @SwitzerlandId),
(UUID(), 'Villigen', @SwitzerlandId),
(UUID(), 'Villnachern', @SwitzerlandId),
(UUID(), 'Windisch', @SwitzerlandId),
(UUID(), 'Bözberg', @SwitzerlandId),
(UUID(), 'Schinznach', @SwitzerlandId),
(UUID(), 'Beinwil am See', @SwitzerlandId),
(UUID(), 'Birrwil', @SwitzerlandId),
(UUID(), 'Burg (AG)', @SwitzerlandId),
(UUID(), 'Dürrenäsch', @SwitzerlandId),
(UUID(), 'Gontenschwil', @SwitzerlandId),
(UUID(), 'Holziken', @SwitzerlandId),
(UUID(), 'Leimbach (AG)', @SwitzerlandId),
(UUID(), 'Leutwil', @SwitzerlandId),
(UUID(), 'Menziken', @SwitzerlandId),
(UUID(), 'Oberkulm', @SwitzerlandId),
(UUID(), 'Reinach (AG)', @SwitzerlandId),
(UUID(), 'Schlossrued', @SwitzerlandId),
(UUID(), 'Schmiedrued', @SwitzerlandId),
(UUID(), 'Schöftland', @SwitzerlandId),
(UUID(), 'Teufenthal (AG)', @SwitzerlandId),
(UUID(), 'Unterkulm', @SwitzerlandId),
(UUID(), 'Zetzwil', @SwitzerlandId),
(UUID(), 'Eiken', @SwitzerlandId),
(UUID(), 'Frick', @SwitzerlandId),
(UUID(), 'Gansingen', @SwitzerlandId),
(UUID(), 'Gipf-Oberfrick', @SwitzerlandId),
(UUID(), 'Herznach', @SwitzerlandId),
(UUID(), 'Hornussen', @SwitzerlandId),
(UUID(), 'Kaisten', @SwitzerlandId),
(UUID(), 'Laufenburg', @SwitzerlandId),
(UUID(), 'Münchwilen (AG)', @SwitzerlandId),
(UUID(), 'Oberhof', @SwitzerlandId),
(UUID(), 'Oeschgen', @SwitzerlandId),
(UUID(), 'Schwaderloch', @SwitzerlandId),
(UUID(), 'Sisseln', @SwitzerlandId),
(UUID(), 'Ueken', @SwitzerlandId),
(UUID(), 'Wittnau', @SwitzerlandId),
(UUID(), 'Wölflinswil', @SwitzerlandId),
(UUID(), 'Zeihen', @SwitzerlandId),
(UUID(), 'Mettauertal', @SwitzerlandId),
(UUID(), 'Ammerswil', @SwitzerlandId),
(UUID(), 'Boniswil', @SwitzerlandId),
(UUID(), 'Brunegg', @SwitzerlandId),
(UUID(), 'Dintikon', @SwitzerlandId),
(UUID(), 'Egliswil', @SwitzerlandId),
(UUID(), 'Fahrwangen', @SwitzerlandId),
(UUID(), 'Hallwil', @SwitzerlandId),
(UUID(), 'Hendschiken', @SwitzerlandId),
(UUID(), 'Holderbank (AG)', @SwitzerlandId),
(UUID(), 'Hunzenschwil', @SwitzerlandId),
(UUID(), 'Lenzburg', @SwitzerlandId),
(UUID(), 'Meisterschwanden', @SwitzerlandId),
(UUID(), 'Möriken-Wildegg', @SwitzerlandId),
(UUID(), 'Niederlenz', @SwitzerlandId),
(UUID(), 'Othmarsingen', @SwitzerlandId),
(UUID(), 'Rupperswil', @SwitzerlandId),
(UUID(), 'Schafisheim', @SwitzerlandId),
(UUID(), 'Seengen', @SwitzerlandId),
(UUID(), 'Seon', @SwitzerlandId),
(UUID(), 'Staufen', @SwitzerlandId),
(UUID(), 'Abtwil', @SwitzerlandId),
(UUID(), 'Aristau', @SwitzerlandId),
(UUID(), 'Auw', @SwitzerlandId),
(UUID(), 'Beinwil (Freiamt)', @SwitzerlandId),
(UUID(), 'Besenbüren', @SwitzerlandId),
(UUID(), 'Bettwil', @SwitzerlandId),
(UUID(), 'Boswil', @SwitzerlandId),
(UUID(), 'Bünzen', @SwitzerlandId),
(UUID(), 'Buttwil', @SwitzerlandId),
(UUID(), 'Dietwil', @SwitzerlandId),
(UUID(), 'Geltwil', @SwitzerlandId),
(UUID(), 'Kallern', @SwitzerlandId),
(UUID(), 'Merenschwand', @SwitzerlandId),
(UUID(), 'Mühlau', @SwitzerlandId),
(UUID(), 'Muri (AG)', @SwitzerlandId),
(UUID(), 'Oberrüti', @SwitzerlandId),
(UUID(), 'Rottenschwil', @SwitzerlandId),
(UUID(), 'Sins', @SwitzerlandId),
(UUID(), 'Waltenschwil', @SwitzerlandId),
(UUID(), 'Hellikon', @SwitzerlandId),
(UUID(), 'Kaiseraugst', @SwitzerlandId),
(UUID(), 'Magden', @SwitzerlandId),
(UUID(), 'Möhlin', @SwitzerlandId),
(UUID(), 'Mumpf', @SwitzerlandId),
(UUID(), 'Obermumpf', @SwitzerlandId),
(UUID(), 'Olsberg', @SwitzerlandId),
(UUID(), 'Rheinfelden', @SwitzerlandId),
(UUID(), 'Schupfart', @SwitzerlandId),
(UUID(), 'Stein (AG)', @SwitzerlandId),
(UUID(), 'Wallbach', @SwitzerlandId),
(UUID(), 'Wegenstetten', @SwitzerlandId),
(UUID(), 'Zeiningen', @SwitzerlandId),
(UUID(), 'Zuzgen', @SwitzerlandId),
(UUID(), 'Aarburg', @SwitzerlandId),
(UUID(), 'Bottenwil', @SwitzerlandId),
(UUID(), 'Brittnau', @SwitzerlandId),
(UUID(), 'Kirchleerau', @SwitzerlandId),
(UUID(), 'Kölliken', @SwitzerlandId),
(UUID(), 'Moosleerau', @SwitzerlandId),
(UUID(), 'Murgenthal', @SwitzerlandId),
(UUID(), 'Oftringen', @SwitzerlandId),
(UUID(), 'Reitnau', @SwitzerlandId),
(UUID(), 'Rothrist', @SwitzerlandId),
(UUID(), 'Safenwil', @SwitzerlandId),
(UUID(), 'Staffelbach', @SwitzerlandId),
(UUID(), 'Strengelbach', @SwitzerlandId),
(UUID(), 'Uerkheim', @SwitzerlandId),
(UUID(), 'Vordemwald', @SwitzerlandId),
(UUID(), 'Wiliberg', @SwitzerlandId),
(UUID(), 'Zofingen', @SwitzerlandId),
(UUID(), 'Baldingen', @SwitzerlandId),
(UUID(), 'Böbikon', @SwitzerlandId),
(UUID(), 'Böttstein', @SwitzerlandId),
(UUID(), 'Döttingen', @SwitzerlandId),
(UUID(), 'Endingen', @SwitzerlandId),
(UUID(), 'Fisibach', @SwitzerlandId),
(UUID(), 'Full-Reuenthal', @SwitzerlandId),
(UUID(), 'Kaiserstuhl', @SwitzerlandId),
(UUID(), 'Klingnau', @SwitzerlandId),
(UUID(), 'Koblenz', @SwitzerlandId),
(UUID(), 'Leibstadt', @SwitzerlandId),
(UUID(), 'Lengnau (AG)', @SwitzerlandId),
(UUID(), 'Leuggern', @SwitzerlandId),
(UUID(), 'Mellikon', @SwitzerlandId),
(UUID(), 'Rekingen (AG)', @SwitzerlandId),
(UUID(), 'Rietheim', @SwitzerlandId),
(UUID(), 'Rümikon', @SwitzerlandId),
(UUID(), 'Schneisingen', @SwitzerlandId),
(UUID(), 'Siglistorf', @SwitzerlandId),
(UUID(), 'Tegerfelden', @SwitzerlandId),
(UUID(), 'Wislikofen', @SwitzerlandId),
(UUID(), 'Bad Zurzach', @SwitzerlandId),
(UUID(), 'Arbon', @SwitzerlandId),
(UUID(), 'Dozwil', @SwitzerlandId),
(UUID(), 'Egnach', @SwitzerlandId),
(UUID(), 'Hefenhofen', @SwitzerlandId),
(UUID(), 'Horn', @SwitzerlandId),
(UUID(), 'Kesswil', @SwitzerlandId),
(UUID(), 'Roggwil (TG)', @SwitzerlandId),
(UUID(), 'Romanshorn', @SwitzerlandId),
(UUID(), 'Salmsach', @SwitzerlandId),
(UUID(), 'Sommeri', @SwitzerlandId),
(UUID(), 'Uttwil', @SwitzerlandId),
(UUID(), 'Amriswil', @SwitzerlandId),
(UUID(), 'Bischofszell', @SwitzerlandId),
(UUID(), 'Erlen', @SwitzerlandId),
(UUID(), 'Hauptwil-Gottshaus', @SwitzerlandId),
(UUID(), 'Hohentannen', @SwitzerlandId),
(UUID(), 'Kradolf-Schönenberg', @SwitzerlandId),
(UUID(), 'Sulgen', @SwitzerlandId),
(UUID(), 'Zihlschlacht-Sitterdorf', @SwitzerlandId),
(UUID(), 'Basadingen-Schlattingen', @SwitzerlandId),
(UUID(), 'Diessenhofen', @SwitzerlandId),
(UUID(), 'Schlatt (TG)', @SwitzerlandId),
(UUID(), 'Aadorf', @SwitzerlandId),
(UUID(), 'Felben-Wellhausen', @SwitzerlandId),
(UUID(), 'Frauenfeld', @SwitzerlandId),
(UUID(), 'Gachnang', @SwitzerlandId),
(UUID(), 'Hüttlingen', @SwitzerlandId),
(UUID(), 'Matzingen', @SwitzerlandId),
(UUID(), 'Neunforn', @SwitzerlandId),
(UUID(), 'Stettfurt', @SwitzerlandId),
(UUID(), 'Thundorf', @SwitzerlandId),
(UUID(), 'Uesslingen-Buch', @SwitzerlandId),
(UUID(), 'Warth-Weiningen', @SwitzerlandId),
(UUID(), 'Altnau', @SwitzerlandId),
(UUID(), 'Bottighofen', @SwitzerlandId),
(UUID(), 'Ermatingen', @SwitzerlandId),
(UUID(), 'Gottlieben', @SwitzerlandId),
(UUID(), 'Güttingen', @SwitzerlandId),
(UUID(), 'Kemmental', @SwitzerlandId),
(UUID(), 'Kreuzlingen', @SwitzerlandId),
(UUID(), 'Langrickenbach', @SwitzerlandId),
(UUID(), 'Lengwil', @SwitzerlandId),
(UUID(), 'Münsterlingen', @SwitzerlandId),
(UUID(), 'Tägerwilen', @SwitzerlandId),
(UUID(), 'Wäldi', @SwitzerlandId),
(UUID(), 'Affeltrangen', @SwitzerlandId),
(UUID(), 'Bettwiesen', @SwitzerlandId),
(UUID(), 'Bichelsee-Balterswil', @SwitzerlandId),
(UUID(), 'Braunau', @SwitzerlandId),
(UUID(), 'Eschlikon', @SwitzerlandId),
(UUID(), 'Fischingen', @SwitzerlandId),
(UUID(), 'Lommis', @SwitzerlandId),
(UUID(), 'Münchwilen (TG)', @SwitzerlandId),
(UUID(), 'Rickenbach (TG)', @SwitzerlandId),
(UUID(), 'Schönholzerswilen', @SwitzerlandId),
(UUID(), 'Sirnach', @SwitzerlandId),
(UUID(), 'Tobel-Tägerschen', @SwitzerlandId),
(UUID(), 'Wängi', @SwitzerlandId),
(UUID(), 'Wilen (TG)', @SwitzerlandId),
(UUID(), 'Wuppenau', @SwitzerlandId),
(UUID(), 'Berlingen', @SwitzerlandId),
(UUID(), 'Eschenz', @SwitzerlandId),
(UUID(), 'Herdern', @SwitzerlandId),
(UUID(), 'Homburg', @SwitzerlandId),
(UUID(), 'Hüttwilen', @SwitzerlandId),
(UUID(), 'Mammern', @SwitzerlandId),
(UUID(), 'Müllheim', @SwitzerlandId),
(UUID(), 'Pfyn', @SwitzerlandId),
(UUID(), 'Raperswilen', @SwitzerlandId),
(UUID(), 'Salenstein', @SwitzerlandId),
(UUID(), 'Steckborn', @SwitzerlandId),
(UUID(), 'Wagenhausen', @SwitzerlandId),
(UUID(), 'Amlikon-Bissegg', @SwitzerlandId),
(UUID(), 'Berg (TG)', @SwitzerlandId),
(UUID(), 'Birwinken', @SwitzerlandId),
(UUID(), 'Bürglen (TG)', @SwitzerlandId),
(UUID(), 'Bussnang', @SwitzerlandId),
(UUID(), 'Märstetten', @SwitzerlandId),
(UUID(), 'Weinfelden', @SwitzerlandId),
(UUID(), 'Wigoltingen', @SwitzerlandId),
(UUID(), 'Arbedo-Castione', @SwitzerlandId),
(UUID(), 'Bellinzona', @SwitzerlandId),
(UUID(), 'Cadenazzo', @SwitzerlandId),
(UUID(), 'Isone', @SwitzerlandId),
(UUID(), 'Lumino', @SwitzerlandId),
(UUID(), 'Sant\'Antonino', @SwitzerlandId),
(UUID(), 'Acquarossa', @SwitzerlandId),
(UUID(), 'Blenio', @SwitzerlandId),
(UUID(), 'Serravalle', @SwitzerlandId),
(UUID(), 'Airolo', @SwitzerlandId),
(UUID(), 'Bedretto', @SwitzerlandId),
(UUID(), 'Bodio', @SwitzerlandId),
(UUID(), 'Dalpe', @SwitzerlandId),
(UUID(), 'Faido', @SwitzerlandId),
(UUID(), 'Giornico', @SwitzerlandId),
(UUID(), 'Personico', @SwitzerlandId),
(UUID(), 'Pollegio', @SwitzerlandId),
(UUID(), 'Prato (Leventina)', @SwitzerlandId),
(UUID(), 'Quinto', @SwitzerlandId),
(UUID(), 'Ascona', @SwitzerlandId),
(UUID(), 'Brione (Verzasca)', @SwitzerlandId),
(UUID(), 'Brione sopra Minusio', @SwitzerlandId),
(UUID(), 'Brissago', @SwitzerlandId),
(UUID(), 'Corippo', @SwitzerlandId),
(UUID(), 'Frasco', @SwitzerlandId),
(UUID(), 'Gordola', @SwitzerlandId),
(UUID(), 'Lavertezzo', @SwitzerlandId),
(UUID(), 'Locarno', @SwitzerlandId),
(UUID(), 'Losone', @SwitzerlandId),
(UUID(), 'Mergoscia', @SwitzerlandId),
(UUID(), 'Minusio', @SwitzerlandId),
(UUID(), 'Muralto', @SwitzerlandId),
(UUID(), 'Orselina', @SwitzerlandId),
(UUID(), 'Ronco sopra Ascona', @SwitzerlandId),
(UUID(), 'Sonogno', @SwitzerlandId),
(UUID(), 'Tenero-Contra', @SwitzerlandId),
(UUID(), 'Vogorno', @SwitzerlandId),
(UUID(), 'Onsernone', @SwitzerlandId),
(UUID(), 'Cugnasco-Gerra', @SwitzerlandId),
(UUID(), 'Agno', @SwitzerlandId),
(UUID(), 'Aranno', @SwitzerlandId),
(UUID(), 'Arogno', @SwitzerlandId),
(UUID(), 'Astano', @SwitzerlandId),
(UUID(), 'Bedano', @SwitzerlandId),
(UUID(), 'Bedigliora', @SwitzerlandId),
(UUID(), 'Bioggio', @SwitzerlandId),
(UUID(), 'Bissone', @SwitzerlandId),
(UUID(), 'Brusino Arsizio', @SwitzerlandId),
(UUID(), 'Cademario', @SwitzerlandId),
(UUID(), 'Cadempino', @SwitzerlandId),
(UUID(), 'Canobbio', @SwitzerlandId),
(UUID(), 'Caslano', @SwitzerlandId),
(UUID(), 'Comano', @SwitzerlandId),
(UUID(), 'Croglio', @SwitzerlandId),
(UUID(), 'Cureglia', @SwitzerlandId),
(UUID(), 'Curio', @SwitzerlandId),
(UUID(), 'Grancia', @SwitzerlandId),
(UUID(), 'Gravesano', @SwitzerlandId),
(UUID(), 'Lamone', @SwitzerlandId),
(UUID(), 'Lugano', @SwitzerlandId),
(UUID(), 'Magliaso', @SwitzerlandId),
(UUID(), 'Manno', @SwitzerlandId),
(UUID(), 'Maroggia', @SwitzerlandId),
(UUID(), 'Massagno', @SwitzerlandId),
(UUID(), 'Melano', @SwitzerlandId),
(UUID(), 'Melide', @SwitzerlandId),
(UUID(), 'Mezzovico-Vira', @SwitzerlandId),
(UUID(), 'Miglieglia', @SwitzerlandId),
(UUID(), 'Monteggio', @SwitzerlandId),
(UUID(), 'Morcote', @SwitzerlandId),
(UUID(), 'Muzzano', @SwitzerlandId),
(UUID(), 'Neggio', @SwitzerlandId),
(UUID(), 'Novaggio', @SwitzerlandId),
(UUID(), 'Origlio', @SwitzerlandId),
(UUID(), 'Paradiso', @SwitzerlandId),
(UUID(), 'Ponte Capriasca', @SwitzerlandId),
(UUID(), 'Ponte Tresa', @SwitzerlandId),
(UUID(), 'Porza', @SwitzerlandId),
(UUID(), 'Pura', @SwitzerlandId),
(UUID(), 'Rovio', @SwitzerlandId),
(UUID(), 'Savosa', @SwitzerlandId),
(UUID(), 'Sessa', @SwitzerlandId),
(UUID(), 'Sorengo', @SwitzerlandId),
(UUID(), 'Capriasca', @SwitzerlandId),
(UUID(), 'Torricella-Taverne', @SwitzerlandId),
(UUID(), 'Vernate', @SwitzerlandId),
(UUID(), 'Vezia', @SwitzerlandId),
(UUID(), 'Vico Morcote', @SwitzerlandId),
(UUID(), 'Collina d\'Oro', @SwitzerlandId),
(UUID(), 'Alto Malcantone', @SwitzerlandId),
(UUID(), 'Monteceneri', @SwitzerlandId),
(UUID(), 'Balerna', @SwitzerlandId),
(UUID(), 'Castel San Pietro', @SwitzerlandId),
(UUID(), 'Chiasso', @SwitzerlandId),
(UUID(), 'Coldrerio', @SwitzerlandId),
(UUID(), 'Mendrisio', @SwitzerlandId),
(UUID(), 'Morbio Inferiore', @SwitzerlandId),
(UUID(), 'Novazzano', @SwitzerlandId),
(UUID(), 'Riva San Vitale', @SwitzerlandId),
(UUID(), 'Stabio', @SwitzerlandId),
(UUID(), 'Vacallo', @SwitzerlandId),
(UUID(), 'Breggia', @SwitzerlandId),
(UUID(), 'Biasca', @SwitzerlandId),
(UUID(), 'Riviera', @SwitzerlandId),
(UUID(), 'Bosco/Gurin', @SwitzerlandId),
(UUID(), 'Campo (Vallemaggia)', @SwitzerlandId),
(UUID(), 'Cerentino', @SwitzerlandId),
(UUID(), 'Cevio', @SwitzerlandId),
(UUID(), 'Linescio', @SwitzerlandId),
(UUID(), 'Maggia', @SwitzerlandId),
(UUID(), 'Lavizzara', @SwitzerlandId),
(UUID(), 'Avegno Gordevio', @SwitzerlandId),
(UUID(), 'C\'za Cadenazzo/Monteceneri', @SwitzerlandId),
(UUID(), 'C\'za Capriasca/Lugano', @SwitzerlandId),
(UUID(), 'Terre di Pedemonte', @SwitzerlandId),
(UUID(), 'Centovalli', @SwitzerlandId),
(UUID(), 'Gambarogno', @SwitzerlandId),
(UUID(), 'Aigle', @SwitzerlandId),
(UUID(), 'Bex', @SwitzerlandId),
(UUID(), 'Chessel', @SwitzerlandId),
(UUID(), 'Corbeyrier', @SwitzerlandId),
(UUID(), 'Gryon', @SwitzerlandId),
(UUID(), 'Lavey-Morcles', @SwitzerlandId),
(UUID(), 'Leysin', @SwitzerlandId),
(UUID(), 'Noville', @SwitzerlandId),
(UUID(), 'Ollon', @SwitzerlandId),
(UUID(), 'Ormont-Dessous', @SwitzerlandId),
(UUID(), 'Ormont-Dessus', @SwitzerlandId),
(UUID(), 'Rennaz', @SwitzerlandId),
(UUID(), 'Roche (VD)', @SwitzerlandId),
(UUID(), 'Villeneuve (VD)', @SwitzerlandId),
(UUID(), 'Yvorne', @SwitzerlandId),
(UUID(), 'Apples', @SwitzerlandId),
(UUID(), 'Aubonne', @SwitzerlandId),
(UUID(), 'Ballens', @SwitzerlandId),
(UUID(), 'Berolle', @SwitzerlandId),
(UUID(), 'Bière', @SwitzerlandId),
(UUID(), 'Bougy-Villars', @SwitzerlandId),
(UUID(), 'Féchy', @SwitzerlandId),
(UUID(), 'Gimel', @SwitzerlandId),
(UUID(), 'Longirod', @SwitzerlandId),
(UUID(), 'Marchissy', @SwitzerlandId),
(UUID(), 'Mollens (VD)', @SwitzerlandId),
(UUID(), 'Montherod', @SwitzerlandId),
(UUID(), 'Saint-George', @SwitzerlandId),
(UUID(), 'Saint-Livres', @SwitzerlandId),
(UUID(), 'Saint-Oyens', @SwitzerlandId),
(UUID(), 'Saubraz', @SwitzerlandId),
(UUID(), 'Avenches', @SwitzerlandId),
(UUID(), 'Cudrefin', @SwitzerlandId),
(UUID(), 'Faoug', @SwitzerlandId),
(UUID(), 'Vully-les-Lacs', @SwitzerlandId),
(UUID(), 'Bettens', @SwitzerlandId),
(UUID(), 'Bournens', @SwitzerlandId),
(UUID(), 'Boussens', @SwitzerlandId),
(UUID(), 'La Chaux (Cossonay)', @SwitzerlandId),
(UUID(), 'Chavannes-le-Veyron', @SwitzerlandId),
(UUID(), 'Chevilly', @SwitzerlandId),
(UUID(), 'Cossonay', @SwitzerlandId),
(UUID(), 'Cottens (VD)', @SwitzerlandId),
(UUID(), 'Cuarnens', @SwitzerlandId),
(UUID(), 'Daillens', @SwitzerlandId),
(UUID(), 'Dizy', @SwitzerlandId),
(UUID(), 'Eclépens', @SwitzerlandId),
(UUID(), 'Ferreyres', @SwitzerlandId),
(UUID(), 'Gollion', @SwitzerlandId),
(UUID(), 'Grancy', @SwitzerlandId),
(UUID(), 'L\'Isle', @SwitzerlandId),
(UUID(), 'Lussery-Villars', @SwitzerlandId),
(UUID(), 'Mauraz', @SwitzerlandId),
(UUID(), 'Mex (VD)', @SwitzerlandId),
(UUID(), 'Moiry', @SwitzerlandId),
(UUID(), 'Mont-la-Ville', @SwitzerlandId),
(UUID(), 'Montricher', @SwitzerlandId),
(UUID(), 'Orny', @SwitzerlandId),
(UUID(), 'Pampigny', @SwitzerlandId),
(UUID(), 'Penthalaz', @SwitzerlandId),
(UUID(), 'Penthaz', @SwitzerlandId),
(UUID(), 'Pompaples', @SwitzerlandId),
(UUID(), 'La Sarraz', @SwitzerlandId),
(UUID(), 'Senarclens', @SwitzerlandId),
(UUID(), 'Sévery', @SwitzerlandId),
(UUID(), 'Sullens', @SwitzerlandId),
(UUID(), 'Vufflens-la-Ville', @SwitzerlandId),
(UUID(), 'Assens', @SwitzerlandId),
(UUID(), 'Bercher', @SwitzerlandId),
(UUID(), 'Bioley-Orjulaz', @SwitzerlandId),
(UUID(), 'Bottens', @SwitzerlandId),
(UUID(), 'Bretigny-sur-Morrens', @SwitzerlandId),
(UUID(), 'Cugy (VD)', @SwitzerlandId),
(UUID(), 'Echallens', @SwitzerlandId),
(UUID(), 'Essertines-sur-Yverdon', @SwitzerlandId),
(UUID(), 'Etagnières', @SwitzerlandId),
(UUID(), 'Fey', @SwitzerlandId),
(UUID(), 'Froideville', @SwitzerlandId),
(UUID(), 'Morrens (VD)', @SwitzerlandId),
(UUID(), 'Oulens-sous-Echallens', @SwitzerlandId),
(UUID(), 'Pailly', @SwitzerlandId),
(UUID(), 'Penthéréaz', @SwitzerlandId),
(UUID(), 'Poliez-Pittet', @SwitzerlandId),
(UUID(), 'Rueyres', @SwitzerlandId),
(UUID(), 'Saint-Barthélemy (VD)', @SwitzerlandId),
(UUID(), 'Villars-le-Terroir', @SwitzerlandId),
(UUID(), 'Vuarrens', @SwitzerlandId),
(UUID(), 'Montilliez', @SwitzerlandId),
(UUID(), 'Goumoëns', @SwitzerlandId),
(UUID(), 'Bonvillars', @SwitzerlandId),
(UUID(), 'Bullet', @SwitzerlandId),
(UUID(), 'Champagne', @SwitzerlandId),
(UUID(), 'Concise', @SwitzerlandId),
(UUID(), 'Corcelles-près-Concise', @SwitzerlandId),
(UUID(), 'Fiez', @SwitzerlandId),
(UUID(), 'Fontaines-sur-Grandson', @SwitzerlandId),
(UUID(), 'Giez', @SwitzerlandId),
(UUID(), 'Grandevent', @SwitzerlandId),
(UUID(), 'Grandson', @SwitzerlandId),
(UUID(), 'Mauborget', @SwitzerlandId),
(UUID(), 'Mutrux', @SwitzerlandId),
(UUID(), 'Novalles', @SwitzerlandId),
(UUID(), 'Onnens (VD)', @SwitzerlandId),
(UUID(), 'Provence', @SwitzerlandId),
(UUID(), 'Sainte-Croix', @SwitzerlandId),
(UUID(), 'Tévenon', @SwitzerlandId),
(UUID(), 'Belmont-sur-Lausanne', @SwitzerlandId),
(UUID(), 'Cheseaux-sur-Lausanne', @SwitzerlandId),
(UUID(), 'Crissier', @SwitzerlandId),
(UUID(), 'Epalinges', @SwitzerlandId),
(UUID(), 'Jouxtens-Mézery', @SwitzerlandId),
(UUID(), 'Lausanne', @SwitzerlandId),
(UUID(), 'Le Mont-sur-Lausanne', @SwitzerlandId),
(UUID(), 'Paudex', @SwitzerlandId),
(UUID(), 'Prilly', @SwitzerlandId),
(UUID(), 'Pully', @SwitzerlandId),
(UUID(), 'Renens (VD)', @SwitzerlandId),
(UUID(), 'Romanel-sur-Lausanne', @SwitzerlandId),
(UUID(), 'Chexbres', @SwitzerlandId),
(UUID(), 'Forel (Lavaux)', @SwitzerlandId),
(UUID(), 'Lutry', @SwitzerlandId),
(UUID(), 'Puidoux', @SwitzerlandId),
(UUID(), 'Rivaz', @SwitzerlandId),
(UUID(), 'Saint-Saphorin (Lavaux)', @SwitzerlandId),
(UUID(), 'Savigny', @SwitzerlandId),
(UUID(), 'Bourg-en-Lavaux', @SwitzerlandId),
(UUID(), 'Aclens', @SwitzerlandId),
(UUID(), 'Bremblens', @SwitzerlandId),
(UUID(), 'Buchillon', @SwitzerlandId),
(UUID(), 'Bussigny', @SwitzerlandId),
(UUID(), 'Bussy-Chardonney', @SwitzerlandId),
(UUID(), 'Chavannes-près-Renens', @SwitzerlandId),
(UUID(), 'Chigny', @SwitzerlandId),
(UUID(), 'Clarmont', @SwitzerlandId),
(UUID(), 'Denens', @SwitzerlandId),
(UUID(), 'Denges', @SwitzerlandId),
(UUID(), 'Echandens', @SwitzerlandId),
(UUID(), 'Echichens', @SwitzerlandId),
(UUID(), 'Ecublens (VD)', @SwitzerlandId),
(UUID(), 'Etoy', @SwitzerlandId),
(UUID(), 'Lavigny', @SwitzerlandId),
(UUID(), 'Lonay', @SwitzerlandId),
(UUID(), 'Lully (VD)', @SwitzerlandId),
(UUID(), 'Lussy-sur-Morges', @SwitzerlandId),
(UUID(), 'Morges', @SwitzerlandId),
(UUID(), 'Préverenges', @SwitzerlandId),
(UUID(), 'Reverolle', @SwitzerlandId),
(UUID(), 'Romanel-sur-Morges', @SwitzerlandId),
(UUID(), 'Saint-Prex', @SwitzerlandId),
(UUID(), 'Saint-Sulpice (VD)', @SwitzerlandId),
(UUID(), 'Tolochenaz', @SwitzerlandId),
(UUID(), 'Vaux-sur-Morges', @SwitzerlandId),
(UUID(), 'Villars-Sainte-Croix', @SwitzerlandId),
(UUID(), 'Villars-sous-Yens', @SwitzerlandId),
(UUID(), 'Vufflens-le-Château', @SwitzerlandId),
(UUID(), 'Vullierens', @SwitzerlandId),
(UUID(), 'Yens', @SwitzerlandId),
(UUID(), 'Boulens', @SwitzerlandId),
(UUID(), 'Bussy-sur-Moudon', @SwitzerlandId),
(UUID(), 'Chavannes-sur-Moudon', @SwitzerlandId),
(UUID(), 'Curtilles', @SwitzerlandId),
(UUID(), 'Dompierre (VD)', @SwitzerlandId),
(UUID(), 'Hermenches', @SwitzerlandId),
(UUID(), 'Lovatens', @SwitzerlandId),
(UUID(), 'Lucens', @SwitzerlandId),
(UUID(), 'Moudon', @SwitzerlandId),
(UUID(), 'Ogens', @SwitzerlandId),
(UUID(), 'Prévonloup', @SwitzerlandId),
(UUID(), 'Rossenges', @SwitzerlandId),
(UUID(), 'Syens', @SwitzerlandId),
(UUID(), 'Villars-le-Comte', @SwitzerlandId),
(UUID(), 'Vucherens', @SwitzerlandId),
(UUID(), 'Montanaire', @SwitzerlandId),
(UUID(), 'Arnex-sur-Nyon', @SwitzerlandId),
(UUID(), 'Arzier-Le Muids', @SwitzerlandId),
(UUID(), 'Bassins', @SwitzerlandId),
(UUID(), 'Begnins', @SwitzerlandId),
(UUID(), 'Bogis-Bossey', @SwitzerlandId),
(UUID(), 'Borex', @SwitzerlandId),
(UUID(), 'Chavannes-de-Bogis', @SwitzerlandId),
(UUID(), 'Chavannes-des-Bois', @SwitzerlandId),
(UUID(), 'Chéserex', @SwitzerlandId),
(UUID(), 'Coinsins', @SwitzerlandId),
(UUID(), 'Commugny', @SwitzerlandId),
(UUID(), 'Coppet', @SwitzerlandId),
(UUID(), 'Crans-près-Céligny', @SwitzerlandId),
(UUID(), 'Crassier', @SwitzerlandId),
(UUID(), 'Duillier', @SwitzerlandId),
(UUID(), 'Eysins', @SwitzerlandId),
(UUID(), 'Founex', @SwitzerlandId),
(UUID(), 'Genolier', @SwitzerlandId),
(UUID(), 'Gingins', @SwitzerlandId),
(UUID(), 'Givrins', @SwitzerlandId),
(UUID(), 'Gland', @SwitzerlandId),
(UUID(), 'Grens', @SwitzerlandId),
(UUID(), 'Mies', @SwitzerlandId),
(UUID(), 'Nyon', @SwitzerlandId),
(UUID(), 'Prangins', @SwitzerlandId),
(UUID(), 'La Rippe', @SwitzerlandId),
(UUID(), 'Saint-Cergue', @SwitzerlandId),
(UUID(), 'Signy-Avenex', @SwitzerlandId),
(UUID(), 'Tannay', @SwitzerlandId),
(UUID(), 'Trélex', @SwitzerlandId),
(UUID(), 'Le Vaud', @SwitzerlandId),
(UUID(), 'Vich', @SwitzerlandId),
(UUID(), 'L\'Abergement', @SwitzerlandId),
(UUID(), 'Agiez', @SwitzerlandId),
(UUID(), 'Arnex-sur-Orbe', @SwitzerlandId),
(UUID(), 'Ballaigues', @SwitzerlandId),
(UUID(), 'Baulmes', @SwitzerlandId),
(UUID(), 'Bavois', @SwitzerlandId),
(UUID(), 'Bofflens', @SwitzerlandId),
(UUID(), 'Bretonnières', @SwitzerlandId),
(UUID(), 'Chavornay', @SwitzerlandId),
(UUID(), 'Les Clées', @SwitzerlandId),
(UUID(), 'Croy', @SwitzerlandId),
(UUID(), 'Juriens', @SwitzerlandId),
(UUID(), 'Lignerolle', @SwitzerlandId),
(UUID(), 'Montcherand', @SwitzerlandId),
(UUID(), 'Orbe', @SwitzerlandId),
(UUID(), 'La Praz', @SwitzerlandId),
(UUID(), 'Premier', @SwitzerlandId),
(UUID(), 'Rances', @SwitzerlandId),
(UUID(), 'Romainmôtier-Envy', @SwitzerlandId),
(UUID(), 'Sergey', @SwitzerlandId),
(UUID(), 'Valeyres-sous-Rances', @SwitzerlandId),
(UUID(), 'Vallorbe', @SwitzerlandId),
(UUID(), 'Vaulion', @SwitzerlandId),
(UUID(), 'Vuiteboeuf', @SwitzerlandId),
(UUID(), 'Corcelles-le-Jorat', @SwitzerlandId),
(UUID(), 'Essertes', @SwitzerlandId),
(UUID(), 'Maracon', @SwitzerlandId),
(UUID(), 'Montpreveyres', @SwitzerlandId),
(UUID(), 'Ropraz', @SwitzerlandId),
(UUID(), 'Servion', @SwitzerlandId),
(UUID(), 'Vulliens', @SwitzerlandId),
(UUID(), 'Jorat-Menthue', @SwitzerlandId),
(UUID(), 'Oron', @SwitzerlandId),
(UUID(), 'Jorat-Mézières', @SwitzerlandId),
(UUID(), 'Champtauroz', @SwitzerlandId),
(UUID(), 'Chevroux', @SwitzerlandId),
(UUID(), 'Corcelles-près-Payerne', @SwitzerlandId),
(UUID(), 'Grandcour', @SwitzerlandId),
(UUID(), 'Henniez', @SwitzerlandId),
(UUID(), 'Missy', @SwitzerlandId),
(UUID(), 'Payerne', @SwitzerlandId),
(UUID(), 'Trey', @SwitzerlandId),
(UUID(), 'Treytorrens (Payerne)', @SwitzerlandId),
(UUID(), 'Villarzel', @SwitzerlandId),
(UUID(), 'Valbroye', @SwitzerlandId),
(UUID(), 'Château-d\'Oex', @SwitzerlandId),
(UUID(), 'Rossinière', @SwitzerlandId),
(UUID(), 'Rougemont', @SwitzerlandId),
(UUID(), 'Allaman', @SwitzerlandId),
(UUID(), 'Bursinel', @SwitzerlandId),
(UUID(), 'Bursins', @SwitzerlandId),
(UUID(), 'Burtigny', @SwitzerlandId),
(UUID(), 'Dully', @SwitzerlandId),
(UUID(), 'Essertines-sur-Rolle', @SwitzerlandId),
(UUID(), 'Gilly', @SwitzerlandId),
(UUID(), 'Luins', @SwitzerlandId),
(UUID(), 'Mont-sur-Rolle', @SwitzerlandId),
(UUID(), 'Perroy', @SwitzerlandId),
(UUID(), 'Rolle', @SwitzerlandId),
(UUID(), 'Tartegnin', @SwitzerlandId),
(UUID(), 'Vinzel', @SwitzerlandId),
(UUID(), 'L\'Abbaye', @SwitzerlandId),
(UUID(), 'Le Chenit', @SwitzerlandId),
(UUID(), 'Le Lieu', @SwitzerlandId),
(UUID(), 'Blonay', @SwitzerlandId),
(UUID(), 'Chardonne', @SwitzerlandId),
(UUID(), 'Corseaux', @SwitzerlandId),
(UUID(), 'Corsier-sur-Vevey', @SwitzerlandId),
(UUID(), 'Jongny', @SwitzerlandId),
(UUID(), 'Montreux', @SwitzerlandId),
(UUID(), 'Saint-Légier-La Chiésaz', @SwitzerlandId),
(UUID(), 'La Tour-de-Peilz', @SwitzerlandId),
(UUID(), 'Vevey', @SwitzerlandId),
(UUID(), 'Veytaux', @SwitzerlandId),
(UUID(), 'Belmont-sur-Yverdon', @SwitzerlandId),
(UUID(), 'Bioley-Magnoux', @SwitzerlandId),
(UUID(), 'Chamblon', @SwitzerlandId),
(UUID(), 'Champvent', @SwitzerlandId),
(UUID(), 'Chavannes-le-Chêne', @SwitzerlandId),
(UUID(), 'Chêne-Pâquier', @SwitzerlandId),
(UUID(), 'Cheseaux-Noréaz', @SwitzerlandId),
(UUID(), 'Cronay', @SwitzerlandId),
(UUID(), 'Cuarny', @SwitzerlandId),
(UUID(), 'Démoret', @SwitzerlandId),
(UUID(), 'Donneloye', @SwitzerlandId),
(UUID(), 'Ependes (VD)', @SwitzerlandId),
(UUID(), 'Mathod', @SwitzerlandId),
(UUID(), 'Molondin', @SwitzerlandId),
(UUID(), 'Montagny-près-Yverdon', @SwitzerlandId),
(UUID(), 'Oppens', @SwitzerlandId),
(UUID(), 'Orges', @SwitzerlandId),
(UUID(), 'Orzens', @SwitzerlandId),
(UUID(), 'Pomy', @SwitzerlandId),
(UUID(), 'Rovray', @SwitzerlandId),
(UUID(), 'Suchy', @SwitzerlandId),
(UUID(), 'Suscévaz', @SwitzerlandId),
(UUID(), 'Treycovagnes', @SwitzerlandId),
(UUID(), 'Ursins', @SwitzerlandId),
(UUID(), 'Valeyres-sous-Montagny', @SwitzerlandId),
(UUID(), 'Valeyres-sous-Ursins', @SwitzerlandId),
(UUID(), 'Villars-Epeney', @SwitzerlandId),
(UUID(), 'Vugelles-La Mothe', @SwitzerlandId),
(UUID(), 'Yverdon-les-Bains', @SwitzerlandId),
(UUID(), 'Yvonand', @SwitzerlandId),
(UUID(), 'Brig-Glis', @SwitzerlandId),
(UUID(), 'Eggerberg', @SwitzerlandId),
(UUID(), 'Naters', @SwitzerlandId),
(UUID(), 'Ried-Brig', @SwitzerlandId),
(UUID(), 'Simplon', @SwitzerlandId),
(UUID(), 'Termen', @SwitzerlandId),
(UUID(), 'Zwischbergen', @SwitzerlandId),
(UUID(), 'Ardon', @SwitzerlandId),
(UUID(), 'Chamoson', @SwitzerlandId),
(UUID(), 'Conthey', @SwitzerlandId),
(UUID(), 'Nendaz', @SwitzerlandId),
(UUID(), 'Vétroz', @SwitzerlandId),
(UUID(), 'Bagnes', @SwitzerlandId),
(UUID(), 'Bourg-Saint-Pierre', @SwitzerlandId),
(UUID(), 'Liddes', @SwitzerlandId),
(UUID(), 'Orsières', @SwitzerlandId),
(UUID(), 'Sembrancher', @SwitzerlandId),
(UUID(), 'Vollèges', @SwitzerlandId),
(UUID(), 'Bellwald', @SwitzerlandId),
(UUID(), 'Binn', @SwitzerlandId),
(UUID(), 'Ernen', @SwitzerlandId),
(UUID(), 'Fiesch', @SwitzerlandId),
(UUID(), 'Fieschertal', @SwitzerlandId),
(UUID(), 'Lax', @SwitzerlandId),
(UUID(), 'Obergoms', @SwitzerlandId),
(UUID(), 'Goms', @SwitzerlandId),
(UUID(), 'Ayent', @SwitzerlandId),
(UUID(), 'Evolène', @SwitzerlandId),
(UUID(), 'Hérémence', @SwitzerlandId),
(UUID(), 'Saint-Martin (VS)', @SwitzerlandId),
(UUID(), 'Vex', @SwitzerlandId),
(UUID(), 'Mont-Noble', @SwitzerlandId),
(UUID(), 'Agarn', @SwitzerlandId),
(UUID(), 'Albinen', @SwitzerlandId),
(UUID(), 'Ergisch', @SwitzerlandId),
(UUID(), 'Inden', @SwitzerlandId),
(UUID(), 'Leuk', @SwitzerlandId),
(UUID(), 'Leukerbad', @SwitzerlandId),
(UUID(), 'Oberems', @SwitzerlandId),
(UUID(), 'Salgesch', @SwitzerlandId),
(UUID(), 'Varen', @SwitzerlandId),
(UUID(), 'Guttet-Feschel', @SwitzerlandId),
(UUID(), 'Gampel-Bratsch', @SwitzerlandId),
(UUID(), 'Turtmann-Unterems', @SwitzerlandId),
(UUID(), 'Bovernier', @SwitzerlandId),
(UUID(), 'Charrat', @SwitzerlandId),
(UUID(), 'Fully', @SwitzerlandId),
(UUID(), 'Isérables', @SwitzerlandId),
(UUID(), 'Leytron', @SwitzerlandId),
(UUID(), 'Martigny', @SwitzerlandId),
(UUID(), 'Martigny-Combe', @SwitzerlandId),
(UUID(), 'Riddes', @SwitzerlandId),
(UUID(), 'Saillon', @SwitzerlandId),
(UUID(), 'Saxon', @SwitzerlandId),
(UUID(), 'Trient', @SwitzerlandId),
(UUID(), 'Champéry', @SwitzerlandId),
(UUID(), 'Collombey-Muraz', @SwitzerlandId),
(UUID(), 'Monthey', @SwitzerlandId),
(UUID(), 'Port-Valais', @SwitzerlandId),
(UUID(), 'Saint-Gingolph', @SwitzerlandId),
(UUID(), 'Troistorrents', @SwitzerlandId),
(UUID(), 'Val-d\'Illiez', @SwitzerlandId),
(UUID(), 'Vionnaz', @SwitzerlandId),
(UUID(), 'Vouvry', @SwitzerlandId),
(UUID(), 'Bister', @SwitzerlandId),
(UUID(), 'Bitsch', @SwitzerlandId),
(UUID(), 'Grengiols', @SwitzerlandId),
(UUID(), 'Riederalp', @SwitzerlandId),
(UUID(), 'Ausserberg', @SwitzerlandId),
(UUID(), 'Blatten', @SwitzerlandId),
(UUID(), 'Bürchen', @SwitzerlandId),
(UUID(), 'Eischoll', @SwitzerlandId),
(UUID(), 'Ferden', @SwitzerlandId),
(UUID(), 'Kippel', @SwitzerlandId),
(UUID(), 'Niedergesteln', @SwitzerlandId),
(UUID(), 'Raron', @SwitzerlandId),
(UUID(), 'Unterbäch', @SwitzerlandId),
(UUID(), 'Wiler (Lötschen)', @SwitzerlandId),
(UUID(), 'Mörel-Filet', @SwitzerlandId),
(UUID(), 'Steg-Hohtenn', @SwitzerlandId),
(UUID(), 'Bettmeralp', @SwitzerlandId),
(UUID(), 'Collonges', @SwitzerlandId),
(UUID(), 'Dorénaz', @SwitzerlandId),
(UUID(), 'Evionnaz', @SwitzerlandId),
(UUID(), 'Finhaut', @SwitzerlandId),
(UUID(), 'Massongex', @SwitzerlandId),
(UUID(), 'Saint-Maurice', @SwitzerlandId),
(UUID(), 'Salvan', @SwitzerlandId),
(UUID(), 'Vernayaz', @SwitzerlandId),
(UUID(), 'Vérossaz', @SwitzerlandId),
(UUID(), 'Chalais', @SwitzerlandId),
(UUID(), 'Chippis', @SwitzerlandId),
(UUID(), 'Grône', @SwitzerlandId),
(UUID(), 'Icogne', @SwitzerlandId),
(UUID(), 'Lens', @SwitzerlandId),
(UUID(), 'Miège', @SwitzerlandId),
(UUID(), 'Saint-Léonard', @SwitzerlandId),
(UUID(), 'Sierre', @SwitzerlandId),
(UUID(), 'Venthône', @SwitzerlandId),
(UUID(), 'Veyras', @SwitzerlandId),
(UUID(), 'Anniviers', @SwitzerlandId),
(UUID(), 'Crans-Montana', @SwitzerlandId),
(UUID(), 'Arbaz', @SwitzerlandId),
(UUID(), 'Grimisuat', @SwitzerlandId),
(UUID(), 'Savièse', @SwitzerlandId),
(UUID(), 'Sion', @SwitzerlandId),
(UUID(), 'Veysonnaz', @SwitzerlandId),
(UUID(), 'Baltschieder', @SwitzerlandId),
(UUID(), 'Eisten', @SwitzerlandId),
(UUID(), 'Embd', @SwitzerlandId),
(UUID(), 'Grächen', @SwitzerlandId),
(UUID(), 'Lalden', @SwitzerlandId),
(UUID(), 'Randa', @SwitzerlandId),
(UUID(), 'Saas-Almagell', @SwitzerlandId),
(UUID(), 'Saas-Balen', @SwitzerlandId),
(UUID(), 'Saas-Fee', @SwitzerlandId),
(UUID(), 'Saas-Grund', @SwitzerlandId),
(UUID(), 'St. Niklaus', @SwitzerlandId),
(UUID(), 'Stalden (VS)', @SwitzerlandId),
(UUID(), 'Staldenried', @SwitzerlandId),
(UUID(), 'Täsch', @SwitzerlandId),
(UUID(), 'Törbel', @SwitzerlandId),
(UUID(), 'Visp', @SwitzerlandId),
(UUID(), 'Visperterminen', @SwitzerlandId),
(UUID(), 'Zeneggen', @SwitzerlandId),
(UUID(), 'Zermatt', @SwitzerlandId),
(UUID(), 'Boudry', @SwitzerlandId),
(UUID(), 'Corcelles-Cormondrèche', @SwitzerlandId),
(UUID(), 'Cortaillod', @SwitzerlandId),
(UUID(), 'Peseux', @SwitzerlandId),
(UUID(), 'Rochefort', @SwitzerlandId),
(UUID(), 'Milvignes', @SwitzerlandId),
(UUID(), 'La Grande Béroche', @SwitzerlandId),
(UUID(), 'La Chaux-de-Fonds', @SwitzerlandId),
(UUID(), 'Les Planchettes', @SwitzerlandId),
(UUID(), 'La Sagne', @SwitzerlandId),
(UUID(), 'Les Brenets', @SwitzerlandId),
(UUID(), 'La Brévine', @SwitzerlandId),
(UUID(), 'Brot-Plamboz', @SwitzerlandId),
(UUID(), 'Le Cerneux-Péquignot', @SwitzerlandId),
(UUID(), 'La Chaux-du-Milieu', @SwitzerlandId),
(UUID(), 'Le Locle', @SwitzerlandId),
(UUID(), 'Les Ponts-de-Martel', @SwitzerlandId),
(UUID(), 'Cornaux', @SwitzerlandId),
(UUID(), 'Cressier (NE)', @SwitzerlandId),
(UUID(), 'Enges', @SwitzerlandId),
(UUID(), 'Hauterive (NE)', @SwitzerlandId),
(UUID(), 'Le Landeron', @SwitzerlandId),
(UUID(), 'Lignières', @SwitzerlandId),
(UUID(), 'Neuchâtel', @SwitzerlandId),
(UUID(), 'Saint-Blaise', @SwitzerlandId),
(UUID(), 'La Tène', @SwitzerlandId),
(UUID(), 'Valangin', @SwitzerlandId),
(UUID(), 'Val-de-Ruz', @SwitzerlandId),
(UUID(), 'La Côte-aux-Fées', @SwitzerlandId),
(UUID(), 'Les Verrières', @SwitzerlandId),
(UUID(), 'Val-de-Travers', @SwitzerlandId),
(UUID(), 'Aire-la-Ville', @SwitzerlandId),
(UUID(), 'Anières', @SwitzerlandId),
(UUID(), 'Avully', @SwitzerlandId),
(UUID(), 'Avusy', @SwitzerlandId),
(UUID(), 'Bardonnex', @SwitzerlandId),
(UUID(), 'Bellevue', @SwitzerlandId),
(UUID(), 'Bernex', @SwitzerlandId),
(UUID(), 'Carouge (GE)', @SwitzerlandId),
(UUID(), 'Cartigny', @SwitzerlandId),
(UUID(), 'Céligny', @SwitzerlandId),
(UUID(), 'Chancy', @SwitzerlandId),
(UUID(), 'Chêne-Bougeries', @SwitzerlandId),
(UUID(), 'Chêne-Bourg', @SwitzerlandId),
(UUID(), 'Choulex', @SwitzerlandId),
(UUID(), 'Collex-Bossy', @SwitzerlandId),
(UUID(), 'Collonge-Bellerive', @SwitzerlandId),
(UUID(), 'Cologny', @SwitzerlandId),
(UUID(), 'Confignon', @SwitzerlandId),
(UUID(), 'Corsier (GE)', @SwitzerlandId),
(UUID(), 'Dardagny', @SwitzerlandId),
(UUID(), 'Genève', @SwitzerlandId),
(UUID(), 'Genthod', @SwitzerlandId),
(UUID(), 'Le Grand-Saconnex', @SwitzerlandId),
(UUID(), 'Gy', @SwitzerlandId),
(UUID(), 'Hermance', @SwitzerlandId),
(UUID(), 'Jussy', @SwitzerlandId),
(UUID(), 'Laconnex', @SwitzerlandId),
(UUID(), 'Lancy', @SwitzerlandId),
(UUID(), 'Meinier', @SwitzerlandId),
(UUID(), 'Meyrin', @SwitzerlandId),
(UUID(), 'Onex', @SwitzerlandId),
(UUID(), 'Perly-Certoux', @SwitzerlandId),
(UUID(), 'Plan-les-Ouates', @SwitzerlandId),
(UUID(), 'Pregny-Chambésy', @SwitzerlandId),
(UUID(), 'Presinge', @SwitzerlandId),
(UUID(), 'Puplinge', @SwitzerlandId),
(UUID(), 'Russin', @SwitzerlandId),
(UUID(), 'Satigny', @SwitzerlandId),
(UUID(), 'Soral', @SwitzerlandId),
(UUID(), 'Thônex', @SwitzerlandId),
(UUID(), 'Troinex', @SwitzerlandId),
(UUID(), 'Vandoeuvres', @SwitzerlandId),
(UUID(), 'Vernier', @SwitzerlandId),
(UUID(), 'Versoix', @SwitzerlandId),
(UUID(), 'Veyrier', @SwitzerlandId),
(UUID(), 'Boécourt', @SwitzerlandId),
(UUID(), 'Bourrignon', @SwitzerlandId),
(UUID(), 'Châtillon (JU)', @SwitzerlandId),
(UUID(), 'Courchapoix', @SwitzerlandId),
(UUID(), 'Courrendlin', @SwitzerlandId),
(UUID(), 'Courroux', @SwitzerlandId),
(UUID(), 'Courtételle', @SwitzerlandId),
(UUID(), 'Delémont', @SwitzerlandId),
(UUID(), 'Develier', @SwitzerlandId),
(UUID(), 'Ederswiler', @SwitzerlandId),
(UUID(), 'Mervelier', @SwitzerlandId),
(UUID(), 'Mettembert', @SwitzerlandId),
(UUID(), 'Movelier', @SwitzerlandId),
(UUID(), 'Pleigne', @SwitzerlandId),
(UUID(), 'Rossemaison', @SwitzerlandId),
(UUID(), 'Saulcy', @SwitzerlandId),
(UUID(), 'Soyhières', @SwitzerlandId),
(UUID(), 'Haute-Sorne', @SwitzerlandId),
(UUID(), 'Val Terbi', @SwitzerlandId),
(UUID(), 'Le Bémont (JU)', @SwitzerlandId),
(UUID(), 'Les Bois', @SwitzerlandId),
(UUID(), 'Les Breuleux', @SwitzerlandId),
(UUID(), 'La Chaux-des-Breuleux', @SwitzerlandId),
(UUID(), 'Les Enfers', @SwitzerlandId),
(UUID(), 'Les Genevez (JU)', @SwitzerlandId),
(UUID(), 'Lajoux (JU)', @SwitzerlandId),
(UUID(), 'Montfaucon', @SwitzerlandId),
(UUID(), 'Muriaux', @SwitzerlandId),
(UUID(), 'Le Noirmont', @SwitzerlandId),
(UUID(), 'Saignelégier', @SwitzerlandId),
(UUID(), 'Saint-Brais', @SwitzerlandId),
(UUID(), 'Soubey', @SwitzerlandId),
(UUID(), 'Alle', @SwitzerlandId),
(UUID(), 'Beurnevésin', @SwitzerlandId),
(UUID(), 'Boncourt', @SwitzerlandId),
(UUID(), 'Bonfol', @SwitzerlandId),
(UUID(), 'Bure', @SwitzerlandId),
(UUID(), 'Coeuve', @SwitzerlandId),
(UUID(), 'Cornol', @SwitzerlandId),
(UUID(), 'Courchavon', @SwitzerlandId),
(UUID(), 'Courgenay', @SwitzerlandId),
(UUID(), 'Courtedoux', @SwitzerlandId),
(UUID(), 'Damphreux', @SwitzerlandId),
(UUID(), 'Fahy', @SwitzerlandId),
(UUID(), 'Fontenais', @SwitzerlandId),
(UUID(), 'Grandfontaine', @SwitzerlandId),
(UUID(), 'Lugnez', @SwitzerlandId),
(UUID(), 'Porrentruy', @SwitzerlandId),
(UUID(), 'Vendlincourt', @SwitzerlandId),
(UUID(), 'Basse-Allaine', @SwitzerlandId),
(UUID(), 'Clos du Doubs', @SwitzerlandId),
(UUID(), 'Haute-Ajoie', @SwitzerlandId),
(UUID(), 'La Baroche', @SwitzerlandId);